/*******************************************************************************
 *  Copyright (c) 2017 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          ECU Building Blocks
 *  COMP_ABBREV      SRV
 ******************************************************************************/

#ifndef COMPONENT_INFO_AUTO_H
#define COMPONENT_INFO_AUTO_H

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file
 *
 *  \ingroup  SRV
 *
 *  \brief    Public definitions of component versions and IDs
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */

/******************************************************************************/
/* PUBLIC DEFINITIONS                                                         */
/******************************************************************************/

#define CML_FUNC_NAME_LEN_MAX       13

#define GENERIC_VERSION_MAJOR (1U)
#define GENERIC_VERSION_MINOR (0U)
#define GENERIC_VERSION_REVISION (0U)
#define GENERIC_ID_NUMBER (0xE7FFU)

#define PIN_VERSION_MAJOR (1U)
#define PIN_VERSION_MINOR (0U)
#define PIN_VERSION_REVISION (0U)
#define PIN_ID_NUMBER (0xE800U)

#define MEM_VERSION_MAJOR (1U)
#define MEM_VERSION_MINOR (0U)
#define MEM_VERSION_REVISION (0U)
#define MEM_ID_NUMBER (0xE002U)


#endif /* COMPONENT_INFO_AUTO_H */
