/*******************************************************************************
 *  Copyright (c) 2017 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          ECU Building Blocks
 *  COMP_ABBREV      SRV
 ******************************************************************************/

#ifndef COMPONENT_INFO_AUTO_HPP
#define COMPONENT_INFO_AUTO_HPP

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file
 *
 *  \ingroup  SRV
 *
 *  \brief    Public definitions of component functions
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */


#include "cml/cml.hpp"
#include "srv/types.hpp"
#include "component_info_auto.h"

/******************************************************************************/
/* PUBLIC DEFINITIONS                                                         */
/******************************************************************************/

namespace icml
{
/******************************************************************************/
/* PUBLIC DATA DECLARATIONS                                                   */
/******************************************************************************/

extern const Module* const* componentTable;
// extern const srv::span<const Module*> componentTable;
extern const Module* defaultModule;

/******************************************************************************/
/* PUBLIC FUNCTION DECLARATIONS                                               */
/******************************************************************************/

// generic.getAPI() / [59391][4097]
// uint16_t major_out - service API version major
// uint16_t minor_out - service API version minor
extern srv::Response GENERIC_getAPIVersion(cml::Handler& cmlHandler);

// generic.getErr() / [59391][4096]
// srv::InstanceID_t index_in - Instance index
// srv::InstanceID_t index_out - Instance index
// ErrorID_t error_out - The error ID from the module
extern srv::Response GENERIC_getPendingErrors(cml::Handler& cmlHandler);

// memcomp.disableAlloc() / [57346][0]
extern srv::Response MEMCOMP_disableAlloc(cml::Handler& cmlHandler);

// memcomp.read() / [57346][4352]
// uint8_t allocatedCapacity_out - Percentage of allocated heap
extern srv::Response MEMCOMP_read(cml::Handler& cmlHandler);


}  // namespace icml

#endif /* COMPONENT_INFO_AUTO_HPP */
