/*******************************************************************************
*   Copyright (c) 2017 BSH Hausgeraete GmbH,
*   Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
*
*   All rights reserved. This program and the accompanying materials
*   are protected by international copyright laws.
*   Please contact copyright holder for licensing information.
*
********************************************************************************
*   PROJECT          IC DBUS
*   COMP_ABBREV      DLL
*******************************************************************************/


/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/**
\if DBus2DLL
\file 
     See Mainpage for a description of Data Link Layer
\endif
*/

/**
\if DBus2DLL
\mainpage DBus2DLL
\else
\file
   Data link layer for D-Bus-2
\endif

\section introDLL Data Link Layer for D-Bus-2

     This layer handles the message reception and transmission close to the bus-hardware, handling the following:
        - wrapping the message data into a frame as described below, which includes message legth,
        TargetAddress, MessageIdentifier, the data of the message and the attached CRC (16 bit),
        all followed by an acknowledgement from the receiving node (or sending node by broadcasts).

     An incoming message will be acknowledged by the data link layer if the current node (communication partner) is addressed.
     On default only one communication partner address is used, but it is possible to replace the default function to
     allow more addresses to be accepted by the current node.

E.g. Communication partner 1 may also respond to messages sent to communication partner Ah (decimal 10).
However, the acknowledgement generated by the node will always use the same address for identification - in this case
communication partner 1 (i.e. if communication partner Ah is addressed, communication partner 1 will acknowledge this message).

Frame: \image html dbusdll.gif

*/
#ifndef DBUSDLL_H__
#define DBUSDLL_H__

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/
#include "bsh_stdinc.h"
#include "LibTypes.h"
#include "LibDefines.h"
#include "mcal/mcal_types.h"
#include "bustypes.h"
#include "bal.h"


/******************************************************************************/
/* DEPENDENCIES                                                               */
/******************************************************************************/
#define DEPLIB_DLL MOD_TIM, ///< dependencies of library module


/******************************************************************************/
/* PUBLIC TYPE DEFINITIONS                                                    */
/******************************************************************************/
/**
TdllConfigurationItem is used for configuring node address, baud-rate (referred to by the configuration index) and input buffer length.

\param ucNodeAddress
Network address for this node\n
\b type       : uint8_t\n

\param ucConfigIndex
Index representing e.g. baudrate and parity.\n
This index is used by the underlaying layer (HAL - Hardware abstraction layer) for the configuration of the UART.\n
\b type       : uint8_t\n

\param ucInputBufferLength
Length of the input buffer\n
\b type       : uint8_t\n

\param ulWaitingTimeOffsetUs
Application specific value (microseconds) added to random waiting time for non service messages.\n
\b type       :uint32_t\n
*/
struct DllConfigurationItem
{
       uint8_t ucNodeAddress;
       uint8_t ucConfigIndex;
       uint8_t ucInputBufferLength;
       uint32_t ulWaitingTimeOffsetUs;
};


/******************************************************************************/
/* PUBLIC DEFINITIONS                                                         */
/******************************************************************************/

/** For transmission a buffer is needed, which can keep as many bytes as needed by the longest used message.*/
#ifndef DLL_TRANSMIT_BUFFER_DATA_LENGTH
#ifdef TENG_INCLUDED
#define DLL_TRANSMIT_BUFFER_DATA_LENGTH 100u
#else
#define DLL_TRANSMIT_BUFFER_DATA_LENGTH 50u
#endif
#endif

/** Receive Buffer */
#ifdef __MESSAGE_INPUT_BUFFER_SIZE
#define DLL_MESSAGE_INPUT_BUFFER_SIZE  __MESSAGE_INPUT_BUFFER_SIZE
#else
#ifdef TENG_INCLUDED
#define DLL_MESSAGE_INPUT_BUFFER_SIZE  0x50
#else
#define DLL_MESSAGE_INPUT_BUFFER_SIZE  0x32
#endif
#endif

/** Node Address */
#ifdef __DBUS_NODE_ADDRESS
#define DLL_NODE_ADDRESS   __DBUS_NODE_ADDRESS
#else
#define DLL_NODE_ADDRESS               0x01    //!<4 bit node address of this communication partner. Range: 0x01 .. 0x0F (0x00 is reserved for broadcast addressing)
#endif

/*Acks*/
#define DLL_ACK_NOT_RECEIVED   ((uint8_t)0x00U)    //!< CommunicationPartner 0 means broadcast, hence it cannot be returned by any (one) communication partner. The AckType 0 is not defined as any acknowledgement which can be returned from any node, hence it is used to signalise a missing acknowledgement.
#define DLL_ACK_BUSY           ((uint8_t)0x03U)    //!< By Full input buffer or message too long for input buffer.
#define DLL_ACK_WRONG          ((uint8_t)0x07U)    //!< Error by reception - wrong crc.
#define DLL_ACK_OK             ((uint8_t)0x0AU)    //!< Successful reception (crc ok).

#define DLL_ACK_TRANSMISSION_ABORTED  ((uint8_t)0x0FU)        //!< This error definition is used to notify the overlying layer when a collision is terminating the ongoing transmission (instead of calling an error function, the less code costing alternative to include this ).

#define DLL_CRC_INIT   0x0000U      //!< Initial value of crc


/******************************************************************************/
/* PRIVATE MACRO FUNCTION DEFINITIONS                                         */
/******************************************************************************/
static inline uint8_t DLL_GET_COMMUNICATION_PARTNER(uint8_t x)           {return ((uint8_t)(((x) & (uint8_t) 0xF0U) >> 4));} //!< Extracts the communication partner from a target address. Upper nibble of TA is communication partner, lower nibble is subsystem. DLL_GET_COMMUNICATION_PARTNER shifts the upper nibble down.
static inline uint8_t DLL_IGNORE_SUBSYSTEM_IN_TARGET_ADDRESS(uint8_t x)  {return ((uint8_t)((x) & (uint8_t)0xF0U));}         //!< Extracts the communication partner from a target address. Upper nibble of TA is communication partner, lower nibble is subsystem. Unlike DLL_GET_COMMUNICATION_PARTNER, the communication partner is not shifted to the lower nibble.
static inline uint8_t DLL_GET_SUBSYSTEM(uint8_t x)                       {return ((uint8_t)((x) & (uint8_t)0x0FU));}         //!< Extracts the subsystem from a target address. Upper nibble of TA is communication partner, lower nibble is subsystem.
static inline uint8_t DLL_GET_ACKNOWLEDGE(uint8_t x)                     {return ((uint8_t)((x) & (uint8_t)0x0FU));}         //!< Extracts the acknowledgement from the acknowledgement-byte received from another communication partner. The Acknowledge-byte consists of the communication partner address in the upper nibble, and the acknowledgement in the lower nibble.


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS                                                   */
/******************************************************************************/
/** Init values */
extern struct DllConfigurationItem DLL_ConfigurationItem;


/******************************************************************************/
/* PUBLIC FUNCTION DECLARATIONS                                               */
/******************************************************************************/

uint32_t DLL_uiCalcCollisionWaitingTime(void);        ///< Function used for calculating the waiting time depending on occurred collisions.

#ifdef RTOS_DBUS_EVENTDRIVEN

/**
 This function must be called, to initialize DLL module for DBusCAN  chip.

 Function is abstracted from DLL_HandleTask() and handles this functionality instead, if RTOS eventdriven DBUS implementation is used.
 It's required, to call (with procssing time of it's dependent functions), as long as "true" was not returned.

\param none

\return
state, if handling is done\n
\b type       : bool\n
\b range      : handling done: true, else false
*
*/
extern bool DLL_moduleInit(void);

/**
 This function must be called, to initialize transmitting a dataframe.

 Function is abstracted from DLL_HandleTask() and handles this functionality instead, if RTOS eventdriven DBUS implementation is used.

\param none

\return
state, if the request to send the DBus message is in progress\n
\b type       : bool\n
\b range      : request complete: true, else false
*
*/
extern bool DLL_sendingInit(void);

/**
 This function is called, if transmitting a dataframe is done.

 Function is abstracted from DLL_HandleTask() and handles this functionality instead, if RTOS eventdriven DBUS implementation is used.

\param none

\return none
*
*/
extern void DLL_sendingDone(void);

/**
 This function is called, if a interrupt from DBusCAN chip is triggered.

 Function is abstracted from DLL_HandleTask() and handles this functionality instead, if RTOS eventdriven DBUS implementation is used.

\param none

\return
state, if handling is done\n
\b type       : bool\n
\b range      : handling done: true, else false
*
*/
extern bool DLL_handleInterrupt(void);

#else

/**
Taskhandler of module DLL, Data Link Layer. This must be called cyclically, at least every 65 ms.

\return
\b type       : uint8_t\n
\b range      : 0 = not initialised, 
              all other values = initialised.
*/
uint8_t DLL_HandleTask(void);
#endif //RTOS_DBUS_EVENTDRIVEN

/**
 Function, which returns a newly received message (if any present) -  the oldest
 not-yet-picked-up message is reported first.

 If the message, which is picked up cannot be processed immediately, this function will return
 the same pointer (to the same message) all the time, until the release function
 (DLL_vReleaseDataFromReceivedMessage) has been called to indicate, that the message
 has been processed, and the data bytes in the input buffer can be used for new incoming messages.
 If no message is present in the input buffer a NULL pointer is returned.

\return
 a pointer to the oldest message, which was received (NULL if none present).
 The data should be transported to the user (typically application) via service functions,
 as the data is not buffered, succeedingly.\n
\b type       : tMessage *

*/
TbusMessage * DLL_ptReceiveMessage(void);

/**
 This function signalises whether the bus is ready for transmission, i.e. that no other node is transmitting
 anything. This function returns true when a message may be transmitted.

\note It is important that this function is not called when receive interrupts are enabled!

\return
\b type       : bool\n
\b range      : 0 = false / not ready, all other values = true / ready

*/
bool DLL_bIsBusReadyForTransmission(void);

/**
DEPRECATED, left for legacy reasons
Function, which may be called to send a message of type TbusMessage onto the bus.

NOT to use for sending of service messages, NOT to use for messages send via BAL with repetitions.
For the purposes mentioned above, DLL_bTransmitMessage is to be used.
In case of Silent Mode, the return value will be false.

\param ptMessageToTransmit
psMessageID is a pointer to the message, which is about to be sent\n
\b type       : TbusMessage

\param uiUserCode
UserCode is any specific code/index/number, which the overlaying layer associates with this specific message.
UserCode is returned by the message completion function: DLL_vMessageTransmitted(uint8_t Acknowledge, uint16_t UserCode).
If there is no valid user code, use the value zero\n
\b type       : uint16_t
\b range      : 0..65535
 */
bool DLL_bSendMessage(TbusMessage *ptMessageToTransmit, uint16_t uiUserCode);

/**
Function called to initiate transmission of a message on the bus.

Whenever bus application layer is implemented this function is to be used instead of
DLL_bSendMessage(tMessage *psMessageToTransmit, uint8_t UserCode),
which is not able to pick up data from a service interface (the second parameter in DLL_bTransmitMessage).

\param tMessageID
psMessageID is a pointer to the message identifier, which is about to be sent\n
\b type       : TbusIdentifier

\param tServiceFunc
ServiceFunc is the interface, where the data, which is about to be sent, can be picked up\n
\b type       : TbusService

\param ucDataLength
Length of the data to be sent.\n
\b type       : uint8_t

\param uiUserCode
UserCode is any specific code/index/number, which the overlaying layer associates with this specific message.
UserCode is returned by the message completion function: DLL_vMessageTransmitted(uint8_t Acknowledge, uint16_t UserCode).
If there is no valid user code, use the value zero\n
\b type       : uint16_t\n
\b range      : 0..65535

\return
\b type       : bool\n
\b range      : 0 = false (meaning: transmission could not be initiated), all other values = true
 (meaning: transmission initiated)

*/

bool DLL_bTransmitMessage(TbusIdentifier tMessageID, TbusService tServiceFunc, uint8_t ucDataLength, uint16_t uiUserCode);

/**
 Function implemented in BAL:

 This function has the opposite message flow of the other functions in DataLinkLayer.
 It is called by data link layer to signalise the layer above that the message has been successfully transmitted
 It is up to the overlaying module, what should be done in this function.

\param ucAcknowledge
Acknowledge from the receiver (or in case of broadcast, the sender)\n
\b type       : uint8_t\n
\b range      : DLL_ACK_NOT_RECEIVED, DLL_ACK_BUSY, DLL_ACK_WRONG and DLL_ACK_OK

\param uiUserCode
The user code is any code/index/numerical value given to DLL from the overlaying layer.
 Hence, this is the confirmation that exactly the message x
 has been transmitted successfully\n
\b type       : uint16_t\n
\b range      : to be defined by the overlaying layer

\return
\b type       : void

*/
void DLL_vMessageTransmitted(uint8_t ucAcknowledge, uint16_t uiUserCode); /* Function prototype, this one is to be defined in the excess template. */

/**
 Function to be defined in the excess template:

 This function has the opposite message flow of the other functions in DataLinkLayer.
 It is called by data link layer to signalise the layer above that the message has been successfully transmitted
 It is up to the overlaying module, what should be done in this function.

\param ucNodeAddress
Node Address of the receiver (or in case of broadcast, the sender)\n
\b type       : uint8_t\n
\b range      : 0x00 to 0xFF

\param ucAcknowledge
Acknowledge from the receiver (or in case of broadcast, the sender)\n
\b type       : uint8_t\n
\b range      : DLL_ACK_NOT_RECEIVED, DLL_ACK_BUSY, DLL_ACK_WRONG and DLL_ACK_OK

\param uiUserCode
The user code is any code/index/numerical value given to DLL from the overlaying layer.
 Hence, this is the confirmation that exactly the message x
 has been transmitted successfully\n
\b type       : uint16_t\n
\b range      : to be defined by the overlaying layer

\return
\b type       : void

*/
void DLL_vMessageTransmitted_UserCallback(uint8_t ucNodeAddress, uint8_t ucAcknowledge, uint16_t uiUserCode); /* Function prototype, this one is to be defined in the excess template. */

/* The following two functions are called in the interrupt. */
void DLL_vHandleRxEvent(void); //!<Mapping from UART receive interrupt to the corresponding data link layer receive handler.
void DLL_vHandleTxEvent(void); //!<Mapping from UART transmit interrupt to the corresponding data link layer transmit handler.

/**
Calling this function releases the data of the last read message in the input (receive) buffer.

\return
\b type       : void

*/
void DLL_vReleaseDataFromReceivedMessage(void);

/**
 Returns the node address of this node.

There is a possibility for the current node to react to more than one node address,
i.e. a node can receive and generate acknowledgment for more than one node address, however, the node address returned by this function will always be used as identity for this node (e.g. this node address is used for the acknowledgement).

\return
The node address of this node\n
\b type       : uint8_t\n
\b Range      : 0x01-0x0F

*/
uint8_t DLL_ucGetMainNodeAddress(void);

/**
 Returns the node address of this node as addressed by the other node. This is useful for subsystem addressing.

There is a possibility for the current node to react to more than one node address,
i.e. a node can receive and generate acknowledgment for more than one node address, however, the node address returned by this function will always be used as identity for this node (e.g. this node address is used for the acknowledgement).

\return
The node address of this node including the subsystem\n
\b type       : uint8_t\n
\b Range      : 0x01-0x0F

*/
uint8_t DLL_ucGetReceivingNodeAddress(void);

/**
 This function is called before entering offline state

 (offline means that this communication partner is logically removed from the bus).
 The only way out of offline mode is through executing a reset.

\return
\b type       : void

*/
void DLL_vGoOffline(void);

/** This interface returns from offline state */
void DLL_vGoOnline(void);

#ifdef LSW_DLL_INCLUDE_STATISTICS
uint8_t DLL_ucGetMaxSucceedingCollisions(void);//!< Interface function for accessing the maximum of succeeding collisions.
uint32_t DLL_ulGetAccumulatedCollisions(void); //!< Interface function for accessing the accumulated collisions.
uint32_t DLL_ulGetCrcErrorCounter(void);//!< Interface function for accessing the Crc error counter.
uint32_t DLL_ulGetAckTimeoutCounter(void);//!< Interface function for accessing the acknowledgement time-out counter.
uint32_t DLL_ulGetOwnAckTimeoutCounter(void);//!< Interface function for accessing the own acknowledgement time-out counter.
uint32_t DLL_ulGetNackCounter(void);//!< Interface function for accessing the missing acknowledgement counter.
uint32_t DLL_ulGetInterbyteTimeoutCounter(void);//!< Interface function for accessing the interbyte time-out counter.
#endif

/** \brief Function to put silent mode active in Dbus2.2*/
void DLL_vSetSilentMode(void);
/** \brief Function to put silent mode out of action in Dbus2.2*/
void DLL_vUnsetSilentMode(void);
/** \brief Function to see silent mode status in Dbus2.2*/
bool DLL_isSilentMode(void);
/** \brief Set Communication Parameters,like, e.g. Interbyte-Time upon baud rate change*/
void DLL_vSetupTimings(uint16_t baud);//!< Set Communication Parameters,like, e.g. Interbyte-Time upon baud rate change
/** \brief Get Information, whether Dbus is either transmitting or receiving data, to know, if action can be started, that would disturb Dbus, such as disabling interrupts.*/
bool DLL_bIsDbusCommunicating(void);

/** \brief Initialize configuration item of DbusDll*/
void DLL_vInitDllConfig(void);
/** \brief In case there are several applications and firmware update on controller.*/
void DLL_vSetupSavedBaudRate(void);
/** \brief Function needed by DLL_vHandleRxEvent(), implementation in dbusdllXs.c*/
bool DLL_bIsCurrentNode(uint8_t ucAddress);
/** \brief Get Information, which config has been used for UART*/
uint8_t DLL_ucGetStandardUartConfigIndex(void);
#ifndef RTOS_DBUS_EVENTDRIVEN
/** \brief Function to set status variable indicating a pending interrupt from DBusCAN chip.*/
void DLL_setDbuscanIrqPending(void);
#endif //RTOS_DBUS_EVENTDRIVEN
/** brief Callback function to handle external interrupt events from DBusCAN chip, implementation in dbusdll_dbuscanXs.c */
void DLL_dbuscanIrqCallback(void *obj, uint32_t flags, const struct MCAL_EventResponse *eventResponse);
/** brief Function to handle failure of transmitting break signal, implementation in dbusdll_dbuscanXs.c */
void DLL_handleBreakTxFailure(const struct BAL_BreakHandler *breakHandler);

#ifdef __cplusplus
}
#endif

#endif
