/*******************************************************************************
 *  Copyright (c) 2017 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          ECU Building Blocks
 *  COMP_ABBREV      SRV
 ******************************************************************************/


/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file
 *
 *  \ingroup  SRV
 *
 *  \brief    Definitions of component functions, IDs and versions
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */

#include "component_info_auto.hpp"
#include <array>
#include "pin_service.hpp"


namespace icml
{

/******************************************************************************/
/* DEFINITONS OF FUNCTION ENTRY TABLES for BBLs with "schema_version" = "0"   */
/******************************************************************************/

// generic functions (ID: generic / 0xE7FF)
constexpr std::array<FunctionEntry, 2U> genericFuncTable {
    FunctionEntry(0x1001U, "getAPI", &GENERIC_getAPIVersion, "", "U16,U16"),
    FunctionEntry(0x1000U, "getErr", &GENERIC_getPendingErrors, "U8=0", "U8,U16")
};
const srv::span<const FunctionEntry> genericFuncTableSpan{genericFuncTable};
const char* const genericTextId = "generic";
constexpr CML_Index_t genericIdNumber {0xE7FFU};

// MEM functions (ID: memcomp / 0xE002)
constexpr std::array<FunctionEntry, 2U> memcompFuncTable {
    FunctionEntry(0x0000U, "disableAlloc", &MEMCOMP_disableAlloc, "", ""),
    FunctionEntry(0x1100U, "read", &MEMCOMP_read, "", "U8")
};
const srv::span<const FunctionEntry> memcompFuncTableSpan{memcompFuncTable};
const char* const memcompTextId = "memcomp";
constexpr CML_Index_t memcompIdNumber {0xE002U};


/******************************************************************************/
/* DEFINITONS OF MODULE STRUCTURES for BBLs with "schema_version" = "0"       */
/******************************************************************************/

// GENERIC module
const Module genericModule = Module(
    genericIdNumber,
    genericTextId,
    {1U, 0U, 0U}, // ComponentVersion {major, minor, revision}
    {0U, 1U}, // ApiVersion {major, minor}
    genericFuncTableSpan,
    2U ///< functionCount
);

// MEM module
const Module memcompModule = Module(
    memcompIdNumber,
    memcompTextId,
    {1U, 0U, 0U}, // ComponentVersion {major, minor, revision}
    {0U, 1U}, // ApiVersion {major, minor}
    memcompFuncTableSpan,
    2U ///< functionCount
);



const std::array<const Module*, 4U> componentTableArray { 
    &genericModule,
    &pinModule,
    &memcompModule,

    (const Module*)nullptr
};
const Module* const* componentTable = componentTableArray.data();
// const srv::span<const Module*> componentTable{componentTableArray};

const Module* defaultModule = &genericModule;


}  // namespace icml
