#ifndef R_GPT_CFG_H_
#define R_GPT_CFG_H_
#define GPT_CFG_PARAM_CHECKING_ENABLE (BSP_CFG_PARAM_CHECKING_ENABLE)
#define GPT_CFG_OUTPUT_SUPPORT_ENABLE (1U)
#define GPT_CFG_WRITE_PROTECT_ENABLE (1U)
#endif /* R_GPT_CFG_H_ */
