/*******************************************************************************
 *  Copyright (c) 2017 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          MCAL
 *  PROCESSOR        STM32G0
 ******************************************************************************/


#ifndef MCAL_CHANNELS_H
#define MCAL_CHANNELS_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file
 *
 *  \ingroup  MCAL
 *
 *  \brief    Public declarations of MCAL channels
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */


/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/

#include "BSH_stdinc.h"
#include "processor.h"
#include "features.h"
#include "mcal/mcal_includes.h"
#include "mcal/mcal.h"

/* Switch off:
   Info 1756: variable 'xx' has 'static' storage duration and non-POD type 'yyy'
   Happens when file included into a cpp-file
 */
/*lint -save -e1756 */
/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MDIO                                          */
/******************************************************************************/

#ifdef MCAL_MDIO_INCLUDED
/* MDIO channels without alternate function */
extern const struct MDIO_Channel MDIOA0;
extern const struct MDIO_Channel MDIOA1;
extern const struct MDIO_Channel MDIOA2;
extern const struct MDIO_Channel MDIOA3;
extern const struct MDIO_Channel MDIOA4;
extern const struct MDIO_Channel MDIOA5;
extern const struct MDIO_Channel MDIOA6;
extern const struct MDIO_Channel MDIOA7;
extern const struct MDIO_Channel MDIOA8;
extern const struct MDIO_Channel MDIOA9;
extern const struct MDIO_Channel MDIOA10;
extern const struct MDIO_Channel MDIOA11;
extern const struct MDIO_Channel MDIOA12;
extern const struct MDIO_Channel MDIOA13;
extern const struct MDIO_Channel MDIOA14;
extern const struct MDIO_Channel MDIOA15;
extern const struct MDIO_Channel MDIOB0;
extern const struct MDIO_Channel MDIOB1;
extern const struct MDIO_Channel MDIOB2;
extern const struct MDIO_Channel MDIOB3;
extern const struct MDIO_Channel MDIOB4;
extern const struct MDIO_Channel MDIOB5;
extern const struct MDIO_Channel MDIOB6;
extern const struct MDIO_Channel MDIOB7;
extern const struct MDIO_Channel MDIOB8;
extern const struct MDIO_Channel MDIOB9;
extern const struct MDIO_Channel MDIOB10;
extern const struct MDIO_Channel MDIOB11;
extern const struct MDIO_Channel MDIOB12;
extern const struct MDIO_Channel MDIOB13;
extern const struct MDIO_Channel MDIOB14;
extern const struct MDIO_Channel MDIOB15;
extern const struct MDIO_Channel MDIOC0;
extern const struct MDIO_Channel MDIOC1;
extern const struct MDIO_Channel MDIOC2;
extern const struct MDIO_Channel MDIOC3;
extern const struct MDIO_Channel MDIOC4;
extern const struct MDIO_Channel MDIOC5;
extern const struct MDIO_Channel MDIOC6;
extern const struct MDIO_Channel MDIOC7;
extern const struct MDIO_Channel MDIOC8;
extern const struct MDIO_Channel MDIOC9;
extern const struct MDIO_Channel MDIOC10;
extern const struct MDIO_Channel MDIOC11;
extern const struct MDIO_Channel MDIOC12;
extern const struct MDIO_Channel MDIOC13;
extern const struct MDIO_Channel MDIOC14;
extern const struct MDIO_Channel MDIOC15;
extern const struct MDIO_Channel MDIOD0;
extern const struct MDIO_Channel MDIOD1;
extern const struct MDIO_Channel MDIOD2;
extern const struct MDIO_Channel MDIOD3;
extern const struct MDIO_Channel MDIOD4;
extern const struct MDIO_Channel MDIOD5;
extern const struct MDIO_Channel MDIOD6;
extern const struct MDIO_Channel MDIOD7;
extern const struct MDIO_Channel MDIOD8;
extern const struct MDIO_Channel MDIOD9;
extern const struct MDIO_Channel MDIOD10;
extern const struct MDIO_Channel MDIOD11;
extern const struct MDIO_Channel MDIOD12;
extern const struct MDIO_Channel MDIOD13;
extern const struct MDIO_Channel MDIOD14;
extern const struct MDIO_Channel MDIOD15;
extern const struct MDIO_Channel MDIOE0;
extern const struct MDIO_Channel MDIOE1;
extern const struct MDIO_Channel MDIOE2;
extern const struct MDIO_Channel MDIOE3;
extern const struct MDIO_Channel MDIOE4;
extern const struct MDIO_Channel MDIOE5;
extern const struct MDIO_Channel MDIOE6;
extern const struct MDIO_Channel MDIOE7;
extern const struct MDIO_Channel MDIOE8;
extern const struct MDIO_Channel MDIOE9;
extern const struct MDIO_Channel MDIOE10;
extern const struct MDIO_Channel MDIOE11;
extern const struct MDIO_Channel MDIOE12;
extern const struct MDIO_Channel MDIOE13;
extern const struct MDIO_Channel MDIOF0;
extern const struct MDIO_Channel MDIOF1;
extern const struct MDIO_Channel MDIOF2;
extern const struct MDIO_Channel MDIOF3;
extern const struct MDIO_Channel MDIOF4;
extern const struct MDIO_Channel MDIOF5;
extern const struct MDIO_Channel MDIOF6;
extern const struct MDIO_Channel MDIOF7;
extern const struct MDIO_Channel MDIOF8;
extern const struct MDIO_Channel MDIOF9;
extern const struct MDIO_Channel MDIOF10;
extern const struct MDIO_Channel MDIOF11;
extern const struct MDIO_Channel MDIOF12;
extern const struct MDIO_Channel MDIOF13;

/* MDIO channels with alternate function */
extern const struct MDIO_Channel MDIOA0_MSPI2_SCK;
extern const struct MDIO_Channel MDIOA0_MTIM2_CH1;
extern const struct MDIO_Channel MDIOA0_MTIM2_ETR;
extern const struct MDIO_Channel MDIOA0_MUART4_TX;
extern const struct MDIO_Channel MDIOA0_MTIMLP1_OUT;
extern const struct MDIO_Channel MDIOA1_MSPI1_SCK;
extern const struct MDIO_Channel MDIOA1_MTIM2_CH2;
extern const struct MDIO_Channel MDIOA1_MUART4_RX;
extern const struct MDIO_Channel MDIOA1_MTIM15_CH1N;
extern const struct MDIO_Channel MDIOA2_MSPI1_MOSI;
extern const struct MDIO_Channel MDIOA2_MUART2_TX;
extern const struct MDIO_Channel MDIOA2_MTIM2_CH3;
extern const struct MDIO_Channel MDIOA2_MTIM15_CH1;
extern const struct MDIO_Channel MDIOA2_MUARTLP1_TX;
extern const struct MDIO_Channel MDIOA3_MSPI2_MISO;
extern const struct MDIO_Channel MDIOA3_MUART2_RX;
extern const struct MDIO_Channel MDIOA3_MTIM2_CH4;
extern const struct MDIO_Channel MDIOA3_MTIM15_CH2;
extern const struct MDIO_Channel MDIOA3_MUARTLP1_RX;
extern const struct MDIO_Channel MDIOA4_MSPI1_NSS;
extern const struct MDIO_Channel MDIOA4_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOA4_MUART6_TX;
extern const struct MDIO_Channel MDIOA4_MTIM14_CH1;
extern const struct MDIO_Channel MDIOA4_MTIMLP2_OUT;
extern const struct MDIO_Channel MDIOA5_MSPI1_SCK;
extern const struct MDIO_Channel MDIOA5_MTIM2_CH1;
extern const struct MDIO_Channel MDIOA5_MTIM2_ETR;
extern const struct MDIO_Channel MDIOA5_MUART6_RX;
extern const struct MDIO_Channel MDIOA5_MUART3_TX;
extern const struct MDIO_Channel MDIOA5_MTIMLP2_ETR;
extern const struct MDIO_Channel MDIOA6_MSPI1_MISO;
extern const struct MDIO_Channel MDIOA6_MTIM3_CH1;
extern const struct MDIO_Channel MDIOA6_MTIM16_CH1;
extern const struct MDIO_Channel MDIOA6_MI2C2_SDA;
extern const struct MDIO_Channel MDIOA6_MI2C3_SDA;
extern const struct MDIO_Channel MDIOA7_MSPI1_MOSI;
extern const struct MDIO_Channel MDIOA7_MTIM3_CH2;
extern const struct MDIO_Channel MDIOA7_MTIM14_CH1;
extern const struct MDIO_Channel MDIOA7_MTIM17_CH1;
extern const struct MDIO_Channel MDIOA7_MI2C2_SCL;
extern const struct MDIO_Channel MDIOA7_MI2C3_SCL;
extern const struct MDIO_Channel MDIOA8_MCO;
extern const struct MDIO_Channel MDIOA8_MSPI2_NSS;
extern const struct MDIO_Channel MDIOA8_MTIM1_CH1;
extern const struct MDIO_Channel MDIOA8_MTIMLP2_OUT;
extern const struct MDIO_Channel MDIOA9_MCO;
extern const struct MDIO_Channel MDIOA9_MUART1_TX;
extern const struct MDIO_Channel MDIOA9_MTIM1_CH2;
extern const struct MDIO_Channel MDIOA9_MSPI2_MISO;
extern const struct MDIO_Channel MDIOA9_MI2C1_SCL;
extern const struct MDIO_Channel MDIOA9_MI2C2_SCL;
extern const struct MDIO_Channel MDIOA10_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOA10_MUART1_RX;
extern const struct MDIO_Channel MDIOA10_MTIM1_CH3;
extern const struct MDIO_Channel MDIOA10_MI2C1_SDA;
extern const struct MDIO_Channel MDIOA10_MI2C2_SDA;
extern const struct MDIO_Channel MDIOA11_MSPI1_MISO;
extern const struct MDIO_Channel MDIOA11_MTIM1_CH4;
extern const struct MDIO_Channel MDIOA11_MI2C2_SCL;
extern const struct MDIO_Channel MDIOA12_MSPI1_MOSI;
extern const struct MDIO_Channel MDIOA12_MTIM1_ETR;
extern const struct MDIO_Channel MDIOA12_MI2C2_SDA;
extern const struct MDIO_Channel MDIOA14_MUART2_TX;
extern const struct MDIO_Channel MDIOA15_MSPI1_NSS;
extern const struct MDIO_Channel MDIOA15_MUART2_RX;
extern const struct MDIO_Channel MDIOA15_MTIM2_CH1;
extern const struct MDIO_Channel MDIOA15_MTIM2_ETR;
extern const struct MDIO_Channel MDIOB0_MSPI1_NSS;
extern const struct MDIO_Channel MDIOB0_MTIM3_CH3;
extern const struct MDIO_Channel MDIOB0_MUART3_RX;
extern const struct MDIO_Channel MDIOB0_MTIMLP1_OUT;
extern const struct MDIO_Channel MDIOB0_MUART5_TX;
extern const struct MDIO_Channel MDIOB1_MTIM14_CH1;
extern const struct MDIO_Channel MDIOB1_MTIM3_CH4;
extern const struct MDIO_Channel MDIOB1_MTIMLP2_IN1;
extern const struct MDIO_Channel MDIOB1_MUART5_RX;
extern const struct MDIO_Channel MDIOB2_MSPI2_MISO;
extern const struct MDIO_Channel MDIOB2_MUART3_TX;
extern const struct MDIO_Channel MDIOB2_MTIMLP1_OUT;
extern const struct MDIO_Channel MDIOB3_MSPI1_SCK;
extern const struct MDIO_Channel MDIOB3_MTIM1_CH2;
extern const struct MDIO_Channel MDIOB3_MUART5_TX;
extern const struct MDIO_Channel MDIOB3_MTIM2_CH2;
extern const struct MDIO_Channel MDIOB3_MI2C3_SCL;
extern const struct MDIO_Channel MDIOB3_MI2C2_SCL;
extern const struct MDIO_Channel MDIOB3_MSPI3_SCK;
extern const struct MDIO_Channel MDIOB4_MSPI1_MISO;
extern const struct MDIO_Channel MDIOB4_MTIM3_CH1;
extern const struct MDIO_Channel MDIOB4_MUART5_RX;
extern const struct MDIO_Channel MDIOB4_MI2C3_SDA;
extern const struct MDIO_Channel MDIOB4_MI2C2_SDA;
extern const struct MDIO_Channel MDIOB4_MSPI3_MISO;
extern const struct MDIO_Channel MDIOB5_MSPI1_MOSI;
extern const struct MDIO_Channel MDIOB5_MTIM3_CH2;
extern const struct MDIO_Channel MDIOB5_MTIMLP1_IN1;
extern const struct MDIO_Channel MDIOB5_MSPI3_MOSI;
extern const struct MDIO_Channel MDIOB6_MUART1_TX;
extern const struct MDIO_Channel MDIOB6_MTIM1_CH3;
extern const struct MDIO_Channel MDIOB6_MSPI2_MISO;
extern const struct MDIO_Channel MDIOB6_MTIMLP1_ETR;
extern const struct MDIO_Channel MDIOB6_MI2C1_SCL;
extern const struct MDIO_Channel MDIOB6_MTIM4_CH1;
extern const struct MDIO_Channel MDIOB6_MUARTLP2_TX;
extern const struct MDIO_Channel MDIOB7_MUART1_RX;
extern const struct MDIO_Channel MDIOB7_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOB7_MTIMLP1_IN2;
extern const struct MDIO_Channel MDIOB7_MI2C1_SDA;
extern const struct MDIO_Channel MDIOB7_MTIM4_CH2;
extern const struct MDIO_Channel MDIOB7_MUARTLP2_RX;
extern const struct MDIO_Channel MDIOB8_MSPI2_SCK;
extern const struct MDIO_Channel MDIOB8_MTIM16_CH1;
extern const struct MDIO_Channel MDIOB8_MUART3_TX;
extern const struct MDIO_Channel MDIOB8_MI2C1_SCL;
extern const struct MDIO_Channel MDIOB8_MUART6_TX;
extern const struct MDIO_Channel MDIOB8_MTIM4_CH3;
extern const struct MDIO_Channel MDIOB9_MTIM17_CH1;
extern const struct MDIO_Channel MDIOB9_MUART3_RX;
extern const struct MDIO_Channel MDIOB9_MSPI2_NSS;
extern const struct MDIO_Channel MDIOB9_MI2C1_SDA;
extern const struct MDIO_Channel MDIOB9_MUART6_RX;
extern const struct MDIO_Channel MDIOB9_MTIM4_CH4;
extern const struct MDIO_Channel MDIOB10_MUARTLP1_RX;
extern const struct MDIO_Channel MDIOB10_MTIM2_CH3;
extern const struct MDIO_Channel MDIOB10_MUART3_TX;
extern const struct MDIO_Channel MDIOB10_MSPI2_SCK;
extern const struct MDIO_Channel MDIOB10_MI2C2_SCL;
extern const struct MDIO_Channel MDIOB11_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOB11_MUARTLP1_TX;
extern const struct MDIO_Channel MDIOB11_MTIM2_CH4;
extern const struct MDIO_Channel MDIOB11_MUART3_RX;
extern const struct MDIO_Channel MDIOB11_MI2C2_SDA;
extern const struct MDIO_Channel MDIOB12_MSPI2_NSS;
extern const struct MDIO_Channel MDIOB13_MSPI2_SCK;
extern const struct MDIO_Channel MDIOB13_MI2C2_SCL;
extern const struct MDIO_Channel MDIOB14_MSPI2_MISO;
extern const struct MDIO_Channel MDIOB14_MTIM15_CH1;
extern const struct MDIO_Channel MDIOB14_MI2C2_SDA;
extern const struct MDIO_Channel MDIOB15_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOB15_MTIM15_CH2;
extern const struct MDIO_Channel MDIOC0_MTIMLP1_IN1;
extern const struct MDIO_Channel MDIOC0_MUARTLP1_RX;
extern const struct MDIO_Channel MDIOC0_MTIMLP2_IN1;
extern const struct MDIO_Channel MDIOC0_MUARTLP2_TX;
extern const struct MDIO_Channel MDIOC0_MUART6_TX;
extern const struct MDIO_Channel MDIOC0_MI2C3_SCL;
extern const struct MDIO_Channel MDIOC1_MTIMLP1_OUT;
extern const struct MDIO_Channel MDIOC1_MUARTLP1_TX;
extern const struct MDIO_Channel MDIOC1_MTIM15_CH1;
extern const struct MDIO_Channel MDIOC1_MUARTLP2_RX;
extern const struct MDIO_Channel MDIOC1_MUART6_RX;
extern const struct MDIO_Channel MDIOC1_MI2C3_SDA;
extern const struct MDIO_Channel MDIOC2_MTIMLP1_IN2;
extern const struct MDIO_Channel MDIOC2_MSPI2_MISO;
extern const struct MDIO_Channel MDIOC2_MTIM15_CH2;
extern const struct MDIO_Channel MDIOC3_MTIMLP1_ETR;
extern const struct MDIO_Channel MDIOC3_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOC3_MTIMLP2_ETR;
extern const struct MDIO_Channel MDIOC4_MUART3_TX;
extern const struct MDIO_Channel MDIOC4_MUART1_TX;
extern const struct MDIO_Channel MDIOC4_MTIM2_CH1;
extern const struct MDIO_Channel MDIOC4_MTIM2_ETR;
extern const struct MDIO_Channel MDIOC5_MUART3_RX;
extern const struct MDIO_Channel MDIOC5_MUART1_RX;
extern const struct MDIO_Channel MDIOC5_MTIM2_CH2;
extern const struct MDIO_Channel MDIOC6_MTIM3_CH1;
extern const struct MDIO_Channel MDIOC6_MTIM2_CH3;
extern const struct MDIO_Channel MDIOC6_MUARTLP2_TX;
extern const struct MDIO_Channel MDIOC7_MTIM3_CH2;
extern const struct MDIO_Channel MDIOC7_MTIM2_CH4;
extern const struct MDIO_Channel MDIOC7_MUARTLP2_RX;
extern const struct MDIO_Channel MDIOC8_MTIM3_CH3;
extern const struct MDIO_Channel MDIOC8_MTIM1_CH1;
extern const struct MDIO_Channel MDIOC9_MTIM3_CH4;
extern const struct MDIO_Channel MDIOC9_MTIM1_CH2;
extern const struct MDIO_Channel MDIOC10_MUART3_TX;
extern const struct MDIO_Channel MDIOC10_MUART4_TX;
extern const struct MDIO_Channel MDIOC10_MTIM1_CH3;
extern const struct MDIO_Channel MDIOC10_MSPI3_SCK;
extern const struct MDIO_Channel MDIOC11_MUART3_RX;
extern const struct MDIO_Channel MDIOC11_MUART4_RX;
extern const struct MDIO_Channel MDIOC11_MTIM1_CH4;
extern const struct MDIO_Channel MDIOC11_MSPI3_MISO;
extern const struct MDIO_Channel MDIOC12_MTIMLP1_IN1;
extern const struct MDIO_Channel MDIOC12_MTIM14_CH1;
extern const struct MDIO_Channel MDIOC12_MUART5_TX;
extern const struct MDIO_Channel MDIOC12_MSPI3_MOSI;
extern const struct MDIO_Channel MDIOD0_MSPI2_NSS;
extern const struct MDIO_Channel MDIOD0_MTIM16_CH1;
extern const struct MDIO_Channel MDIOD1_MSPI2_SCK;
extern const struct MDIO_Channel MDIOD1_MTIM17_CH1;
extern const struct MDIO_Channel MDIOD2_MTIM3_ETR;
extern const struct MDIO_Channel MDIOD2_MUART5_RX;
extern const struct MDIO_Channel MDIOD3_MSPI2_MISO;
extern const struct MDIO_Channel MDIOD3_MUART5_TX;
extern const struct MDIO_Channel MDIOD4_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOD5_MUART2_TX;
extern const struct MDIO_Channel MDIOD5_MSPI1_MISO;
extern const struct MDIO_Channel MDIOD6_MUART2_RX;
extern const struct MDIO_Channel MDIOD6_MSPI1_MOSI;
extern const struct MDIO_Channel MDIOD6_MTIMLP2_OUT;
extern const struct MDIO_Channel MDIOD8_MUART3_TX;
extern const struct MDIO_Channel MDIOD8_MSPI1_SCK;
extern const struct MDIO_Channel MDIOD8_MTIMLP1_OUT;
extern const struct MDIO_Channel MDIOD9_MUART3_RX;
extern const struct MDIO_Channel MDIOD9_MSPI1_NSS;
extern const struct MDIO_Channel MDIOD12_MTIM4_CH1;
extern const struct MDIO_Channel MDIOD13_MTIM4_CH2;
extern const struct MDIO_Channel MDIOD14_MTIM4_CH3;
extern const struct MDIO_Channel MDIOD15_MTIM4_CH4;
extern const struct MDIO_Channel MDIOE0_MTIM16_CH1;
extern const struct MDIO_Channel MDIOE1_MTIM17_CH1;
extern const struct MDIO_Channel MDIOE2_MTIM3_ETR;
extern const struct MDIO_Channel MDIOE3_MTIM3_CH1;
extern const struct MDIO_Channel MDIOE4_MTIM3_CH2;
extern const struct MDIO_Channel MDIOE5_MTIM3_CH3;
extern const struct MDIO_Channel MDIOE6_MTIM3_CH4;
extern const struct MDIO_Channel MDIOE7_MTIM1_ETR;
extern const struct MDIO_Channel MDIOE8_MUART4_TX;
extern const struct MDIO_Channel MDIOE8_MTIM1_CH1N;
extern const struct MDIO_Channel MDIOE9_MUART4_RX;
extern const struct MDIO_Channel MDIOE9_MTIM1_CH1;
extern const struct MDIO_Channel MDIOE10_MTIM1_CH2N;
extern const struct MDIO_Channel MDIOE10_MUART5_TX;
extern const struct MDIO_Channel MDIOE11_MTIM1_CH2;
extern const struct MDIO_Channel MDIOE11_MUART5_RX;
extern const struct MDIO_Channel MDIOE12_MTIM1_CH3N;
extern const struct MDIO_Channel MDIOE13_MTIM1_CH3N;
extern const struct MDIO_Channel MDIOF0_MTIM14_CH1;
extern const struct MDIO_Channel MDIOF2_MUARTLP2_TX;
extern const struct MDIO_Channel MDIOF3_MUARTLP2_RX;
extern const struct MDIO_Channel MDIOF4_MUARTLP1_TX;
extern const struct MDIO_Channel MDIOF5_MUARTLP1_RX;
extern const struct MDIO_Channel MDIOF9_MUART6_TX;
extern const struct MDIO_Channel MDIOF10_MUART6_RX;
extern const struct MDIO_Channel MDIOF12_MTIM15_CH1;
extern const struct MDIO_Channel MDIOF13_MTIM15_CH2;

#endif /* MCAL_MDIO_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MEXTI                                         */
/******************************************************************************/

#ifdef MCAL_MEXTI_INCLUDED
/* MEXTI channels without alternate function */
extern const struct MEXTI_Channel MEXTIA0;
extern const struct MEXTI_Channel MEXTIA1;
extern const struct MEXTI_Channel MEXTIA2;
extern const struct MEXTI_Channel MEXTIA3;
extern const struct MEXTI_Channel MEXTIA4;
extern const struct MEXTI_Channel MEXTIA5;
extern const struct MEXTI_Channel MEXTIA6;
extern const struct MEXTI_Channel MEXTIA7;
extern const struct MEXTI_Channel MEXTIA8;
extern const struct MEXTI_Channel MEXTIA9;
extern const struct MEXTI_Channel MEXTIA10;
extern const struct MEXTI_Channel MEXTIA11;
extern const struct MEXTI_Channel MEXTIA12;
extern const struct MEXTI_Channel MEXTIA13;
extern const struct MEXTI_Channel MEXTIA14;
extern const struct MEXTI_Channel MEXTIA15;
extern const struct MEXTI_Channel MEXTIB0;
extern const struct MEXTI_Channel MEXTIB1;
extern const struct MEXTI_Channel MEXTIB2;
extern const struct MEXTI_Channel MEXTIB3;
extern const struct MEXTI_Channel MEXTIB4;
extern const struct MEXTI_Channel MEXTIB5;
extern const struct MEXTI_Channel MEXTIB6;
extern const struct MEXTI_Channel MEXTIB7;
extern const struct MEXTI_Channel MEXTIB8;
extern const struct MEXTI_Channel MEXTIB9;
extern const struct MEXTI_Channel MEXTIB10;
extern const struct MEXTI_Channel MEXTIB11;
extern const struct MEXTI_Channel MEXTIB12;
extern const struct MEXTI_Channel MEXTIB13;
extern const struct MEXTI_Channel MEXTIB14;
extern const struct MEXTI_Channel MEXTIB15;
extern const struct MEXTI_Channel MEXTIC0;
extern const struct MEXTI_Channel MEXTIC1;
extern const struct MEXTI_Channel MEXTIC2;
extern const struct MEXTI_Channel MEXTIC3;
extern const struct MEXTI_Channel MEXTIC4;
extern const struct MEXTI_Channel MEXTIC5;
extern const struct MEXTI_Channel MEXTIC6;
extern const struct MEXTI_Channel MEXTIC7;
extern const struct MEXTI_Channel MEXTIC8;
extern const struct MEXTI_Channel MEXTIC9;
extern const struct MEXTI_Channel MEXTIC10;
extern const struct MEXTI_Channel MEXTIC11;
extern const struct MEXTI_Channel MEXTIC12;
extern const struct MEXTI_Channel MEXTIC13;
extern const struct MEXTI_Channel MEXTIC14;
extern const struct MEXTI_Channel MEXTIC15;
extern const struct MEXTI_Channel MEXTID0;
extern const struct MEXTI_Channel MEXTID1;
extern const struct MEXTI_Channel MEXTID2;
extern const struct MEXTI_Channel MEXTID3;
extern const struct MEXTI_Channel MEXTID4;
extern const struct MEXTI_Channel MEXTID5;
extern const struct MEXTI_Channel MEXTID6;
extern const struct MEXTI_Channel MEXTID7;
extern const struct MEXTI_Channel MEXTID8;
extern const struct MEXTI_Channel MEXTID9;
extern const struct MEXTI_Channel MEXTID10;
extern const struct MEXTI_Channel MEXTID11;
extern const struct MEXTI_Channel MEXTID12;
extern const struct MEXTI_Channel MEXTID13;
extern const struct MEXTI_Channel MEXTID14;
extern const struct MEXTI_Channel MEXTID15;
extern const struct MEXTI_Channel MEXTIE0;
extern const struct MEXTI_Channel MEXTIE1;
extern const struct MEXTI_Channel MEXTIE2;
extern const struct MEXTI_Channel MEXTIE3;
extern const struct MEXTI_Channel MEXTIE4;
extern const struct MEXTI_Channel MEXTIE5;
extern const struct MEXTI_Channel MEXTIE6;
extern const struct MEXTI_Channel MEXTIE7;
extern const struct MEXTI_Channel MEXTIE8;
extern const struct MEXTI_Channel MEXTIE9;
extern const struct MEXTI_Channel MEXTIE10;
extern const struct MEXTI_Channel MEXTIE11;
extern const struct MEXTI_Channel MEXTIE12;
extern const struct MEXTI_Channel MEXTIE13;
extern const struct MEXTI_Channel MEXTIF0;
extern const struct MEXTI_Channel MEXTIF1;
extern const struct MEXTI_Channel MEXTIF2;
extern const struct MEXTI_Channel MEXTIF3;
extern const struct MEXTI_Channel MEXTIF4;
extern const struct MEXTI_Channel MEXTIF5;
extern const struct MEXTI_Channel MEXTIF6;
extern const struct MEXTI_Channel MEXTIF7;
extern const struct MEXTI_Channel MEXTIF8;
extern const struct MEXTI_Channel MEXTIF9;
extern const struct MEXTI_Channel MEXTIF10;
extern const struct MEXTI_Channel MEXTIF11;
extern const struct MEXTI_Channel MEXTIF12;
extern const struct MEXTI_Channel MEXTIF13;

#endif /* MCAL_MEXTI_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MUART                                         */
/******************************************************************************/

#ifdef MCAL_MUART_INCLUDED
/* MUART channels */
#ifdef MUART1_PRESENT
extern const struct MUART_Channel MUART1_RX_PA10_TX_PA9;
extern const struct MUART_Channel MUART1_RX_PA10_TX_PB6;
extern const struct MUART_Channel MUART1_RX_PA10_TX_PC4;
extern const struct MUART_Channel MUART1_RX_PB7_TX_PA9;
extern const struct MUART_Channel MUART1_RX_PB7_TX_PB6;
extern const struct MUART_Channel MUART1_RX_PB7_TX_PC4;
extern const struct MUART_Channel MUART1_RX_PC5_TX_PA9;
extern const struct MUART_Channel MUART1_RX_PC5_TX_PB6;
extern const struct MUART_Channel MUART1_RX_PC5_TX_PC4;

#endif /* MUART1_PRESENT */

#ifdef MUART2_PRESENT
extern const struct MUART_Channel MUART2_RX_PA3_TX_PA2;
extern const struct MUART_Channel MUART2_RX_PA3_TX_PA14;
extern const struct MUART_Channel MUART2_RX_PA3_TX_PD5;
extern const struct MUART_Channel MUART2_RX_PA15_TX_PA2;
extern const struct MUART_Channel MUART2_RX_PA15_TX_PA14;
extern const struct MUART_Channel MUART2_RX_PA15_TX_PD5;
extern const struct MUART_Channel MUART2_RX_PD6_TX_PA2;
extern const struct MUART_Channel MUART2_RX_PD6_TX_PA14;
extern const struct MUART_Channel MUART2_RX_PD6_TX_PD5;

#endif /* MUART2_PRESENT */

#ifdef MUART3_PRESENT
extern const struct MUART_Channel MUART3_RX_PB0_TX_PA5;
extern const struct MUART_Channel MUART3_RX_PB0_TX_PB2;
extern const struct MUART_Channel MUART3_RX_PB0_TX_PB8;
extern const struct MUART_Channel MUART3_RX_PB0_TX_PB10;
extern const struct MUART_Channel MUART3_RX_PB0_TX_PC4;
extern const struct MUART_Channel MUART3_RX_PB0_TX_PC10;
extern const struct MUART_Channel MUART3_RX_PB0_TX_PD8;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PA5;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PB2;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PB8;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PB10;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PC4;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PC10;
extern const struct MUART_Channel MUART3_RX_PB9_TX_PD8;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PA5;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PB2;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PB8;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PB10;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PC4;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PC10;
extern const struct MUART_Channel MUART3_RX_PB11_TX_PD8;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PA5;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PB2;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PB8;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PB10;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PC4;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PC10;
extern const struct MUART_Channel MUART3_RX_PC5_TX_PD8;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PA5;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PB2;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PB8;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PB10;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PC4;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PC10;
extern const struct MUART_Channel MUART3_RX_PC11_TX_PD8;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PA5;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PB2;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PB8;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PB10;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PC4;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PC10;
extern const struct MUART_Channel MUART3_RX_PD9_TX_PD8;

#endif /* MUART3_PRESENT */

#ifdef MUART4_PRESENT
extern const struct MUART_Channel MUART4_RX_PA1_TX_PA0;
extern const struct MUART_Channel MUART4_RX_PA1_TX_PC10;
extern const struct MUART_Channel MUART4_RX_PA1_TX_PE8;
extern const struct MUART_Channel MUART4_RX_PC11_TX_PA0;
extern const struct MUART_Channel MUART4_RX_PC11_TX_PC10;
extern const struct MUART_Channel MUART4_RX_PC11_TX_PE8;
extern const struct MUART_Channel MUART4_RX_PE9_TX_PA0;
extern const struct MUART_Channel MUART4_RX_PE9_TX_PC10;
extern const struct MUART_Channel MUART4_RX_PE9_TX_PE8;

#endif /* MUART4_PRESENT */

#ifdef MUART5_PRESENT
extern const struct MUART_Channel MUART5_RX_PB4_TX_PB3;
extern const struct MUART_Channel MUART5_RX_PB4_TX_PB0;
extern const struct MUART_Channel MUART5_RX_PB4_TX_PC12;
extern const struct MUART_Channel MUART5_RX_PB4_TX_PD3;
extern const struct MUART_Channel MUART5_RX_PB4_TX_PE10;
extern const struct MUART_Channel MUART5_RX_PB1_TX_PB3;
extern const struct MUART_Channel MUART5_RX_PB1_TX_PB0;
extern const struct MUART_Channel MUART5_RX_PB1_TX_PC12;
extern const struct MUART_Channel MUART5_RX_PB1_TX_PD3;
extern const struct MUART_Channel MUART5_RX_PB1_TX_PE10;
extern const struct MUART_Channel MUART5_RX_PD2_TX_PB3;
extern const struct MUART_Channel MUART5_RX_PD2_TX_PB0;
extern const struct MUART_Channel MUART5_RX_PD2_TX_PC12;
extern const struct MUART_Channel MUART5_RX_PD2_TX_PD3;
extern const struct MUART_Channel MUART5_RX_PD2_TX_PE10;
extern const struct MUART_Channel MUART5_RX_PE11_TX_PB3;
extern const struct MUART_Channel MUART5_RX_PE11_TX_PB0;
extern const struct MUART_Channel MUART5_RX_PE11_TX_PC12;
extern const struct MUART_Channel MUART5_RX_PE11_TX_PD3;
extern const struct MUART_Channel MUART5_RX_PE11_TX_PE10;

#endif /* MUART5_PRESENT */

#ifdef MUART6_PRESENT
extern const struct MUART_Channel MUART6_RX_PA5_TX_PA4;
extern const struct MUART_Channel MUART6_RX_PA5_TX_PB8;
extern const struct MUART_Channel MUART6_RX_PA5_TX_PC0;
extern const struct MUART_Channel MUART6_RX_PA5_TX_PF9;
extern const struct MUART_Channel MUART6_RX_PB9_TX_PA4;
extern const struct MUART_Channel MUART6_RX_PB9_TX_PB8;
extern const struct MUART_Channel MUART6_RX_PB9_TX_PC0;
extern const struct MUART_Channel MUART6_RX_PB9_TX_PF9;
extern const struct MUART_Channel MUART6_RX_PC1_TX_PA4;
extern const struct MUART_Channel MUART6_RX_PC1_TX_PB8;
extern const struct MUART_Channel MUART6_RX_PC1_TX_PC0;
extern const struct MUART_Channel MUART6_RX_PC1_TX_PF9;
extern const struct MUART_Channel MUART6_RX_PF10_TX_PA4;
extern const struct MUART_Channel MUART6_RX_PF10_TX_PB8;
extern const struct MUART_Channel MUART6_RX_PF10_TX_PC0;
extern const struct MUART_Channel MUART6_RX_PF10_TX_PF9;

#endif /* MUART6_PRESENT */

#ifdef MUARTLP1_PRESENT
extern const struct MUART_Channel MUARTLP1_RX_PA3_TX_PA2;
extern const struct MUART_Channel MUARTLP1_RX_PA3_TX_PB11;
extern const struct MUART_Channel MUARTLP1_RX_PA3_TX_PC1;
extern const struct MUART_Channel MUARTLP1_RX_PB10_TX_PA2;
extern const struct MUART_Channel MUARTLP1_RX_PB10_TX_PB11;
extern const struct MUART_Channel MUARTLP1_RX_PB10_TX_PC1;
extern const struct MUART_Channel MUARTLP1_RX_PC0_TX_PA2;
extern const struct MUART_Channel MUARTLP1_RX_PC0_TX_PB11;
extern const struct MUART_Channel MUARTLP1_RX_PC0_TX_PC1;

#endif /* MUARTLP1_PRESENT */

#ifdef MUARTLP2_PRESENT
extern const struct MUART_Channel MUARTLP2_RX_PB7_TX_PB6;
extern const struct MUART_Channel MUARTLP2_RX_PB7_TX_PC0;
extern const struct MUART_Channel MUARTLP2_RX_PB7_TX_PC6;
extern const struct MUART_Channel MUARTLP2_RX_PB7_TX_PF2;
extern const struct MUART_Channel MUARTLP2_RX_PC1_TX_PB6;
extern const struct MUART_Channel MUARTLP2_RX_PC1_TX_PC0;
extern const struct MUART_Channel MUARTLP2_RX_PC1_TX_PC6;
extern const struct MUART_Channel MUARTLP2_RX_PC1_TX_PF2;
extern const struct MUART_Channel MUARTLP2_RX_PC7_TX_PB6;
extern const struct MUART_Channel MUARTLP2_RX_PC7_TX_PC0;
extern const struct MUART_Channel MUARTLP2_RX_PC7_TX_PC6;
extern const struct MUART_Channel MUARTLP2_RX_PC7_TX_PF2;
extern const struct MUART_Channel MUARTLP2_RX_PF3_TX_PB6;
extern const struct MUART_Channel MUARTLP2_RX_PF3_TX_PC0;
extern const struct MUART_Channel MUARTLP2_RX_PF3_TX_PC6;
extern const struct MUART_Channel MUARTLP2_RX_PF3_TX_PF2;

#endif /* MUARTLP2_PRESENT */


#endif /* MCAL_MUART_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MADC                                          */
/******************************************************************************/

#ifdef MCAL_MADC_INCLUDED
/* MADC peripherals with SW trigger */
extern const struct MADC_Periph MADC1;

/* MADC peripherals with HW trigger */
extern const struct MADC_Periph MADC1_TRIG_TIM1_TRGO2;
extern const struct MADC_Periph MADC1_TRIG_TIM1_CC4;
extern const struct MADC_Periph MADC1_TRIG_TIM2_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM3_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM15_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM6_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM4_TRGO;
extern const struct MADC_Periph MADC1_TRIG_EXTI11;

/* MADC channels */
extern const struct MADC_Channel MADC1_IN0_PA0;
extern const struct MADC_Channel MADC1_IN1_PA1;
extern const struct MADC_Channel MADC1_IN2_PA2;
extern const struct MADC_Channel MADC1_IN3_PA3;
extern const struct MADC_Channel MADC1_IN4_PA4;
extern const struct MADC_Channel MADC1_IN5_PA5;
extern const struct MADC_Channel MADC1_IN6_PA6;
extern const struct MADC_Channel MADC1_IN7_PA7;
extern const struct MADC_Channel MADC1_IN8_PB0;
extern const struct MADC_Channel MADC1_IN9_PB1;
extern const struct MADC_Channel MADC1_IN10_PB2;
extern const struct MADC_Channel MADC1_IN11_PB10;
extern const struct MADC_Channel MADC1_IN15_PB11;

#endif /* MCAL_MADC_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MTIM                                          */
/******************************************************************************/

#ifdef MCAL_MTIM_INCLUDED
#ifdef MTIM1_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM1;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM1_PA12;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM1_CH1;
extern const struct MTIM_Channel MTIM1_CH2;
extern const struct MTIM_Channel MTIM1_CH3;
extern const struct MTIM_Channel MTIM1_CH4;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM1_CH1_PA8;
extern const struct MTIM_Channel MTIM1_CH1_PC8;
extern const struct MTIM_Channel MTIM1_CH2_PA9;
extern const struct MTIM_Channel MTIM1_CH2_PC9;
extern const struct MTIM_Channel MTIM1_CH3_PA10;
extern const struct MTIM_Channel MTIM1_CH3_PC10;
extern const struct MTIM_Channel MTIM1_CH4_PA11;
extern const struct MTIM_Channel MTIM1_CH4_PC11;

#endif /* MTIM1_PRESENT */

#ifdef MTIM2_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM2;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM2_PA0;
extern const struct MTIM_Timer MTIM2_PA5;
extern const struct MTIM_Timer MTIM2_PA15;
extern const struct MTIM_Timer MTIM2_PC4;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM2_CH1;
extern const struct MTIM_Channel MTIM2_CH2;
extern const struct MTIM_Channel MTIM2_CH3;
extern const struct MTIM_Channel MTIM2_CH4;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM2_CH1_PA0;
extern const struct MTIM_Channel MTIM2_CH1_PA5;
extern const struct MTIM_Channel MTIM2_CH1_PA15;
extern const struct MTIM_Channel MTIM2_CH1_PC4;
extern const struct MTIM_Channel MTIM2_CH2_PA1;
extern const struct MTIM_Channel MTIM2_CH2_PB3;
extern const struct MTIM_Channel MTIM2_CH2_PC5;
extern const struct MTIM_Channel MTIM2_CH3_PA2;
extern const struct MTIM_Channel MTIM2_CH3_PB10;
extern const struct MTIM_Channel MTIM2_CH3_PC6;
extern const struct MTIM_Channel MTIM2_CH4_PA3;
extern const struct MTIM_Channel MTIM2_CH4_PB11;
extern const struct MTIM_Channel MTIM2_CH4_PC7;

#endif /* MTIM2_PRESENT */

#ifdef MTIM3_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM3;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM3_PD2;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM3_CH1;
extern const struct MTIM_Channel MTIM3_CH2;
extern const struct MTIM_Channel MTIM3_CH3;
extern const struct MTIM_Channel MTIM3_CH4;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM3_CH1_PA6;
extern const struct MTIM_Channel MTIM3_CH1_PB4;
extern const struct MTIM_Channel MTIM3_CH1_PC6;
extern const struct MTIM_Channel MTIM3_CH2_PA7;
extern const struct MTIM_Channel MTIM3_CH2_PB5;
extern const struct MTIM_Channel MTIM3_CH2_PC7;
extern const struct MTIM_Channel MTIM3_CH2_PE4;
extern const struct MTIM_Channel MTIM3_CH3_PB0;
extern const struct MTIM_Channel MTIM3_CH3_PC8;
extern const struct MTIM_Channel MTIM3_CH3_PE5;
extern const struct MTIM_Channel MTIM3_CH4_PB1;
extern const struct MTIM_Channel MTIM3_CH4_PC9;

#endif /* MTIM3_PRESENT */

#ifdef MTIM4_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM4;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM4_CH1;
extern const struct MTIM_Channel MTIM4_CH2;
extern const struct MTIM_Channel MTIM4_CH3;
extern const struct MTIM_Channel MTIM4_CH4;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM4_CH1_PB6;
extern const struct MTIM_Channel MTIM4_CH1_PD12;
extern const struct MTIM_Channel MTIM4_CH2_PB7;
extern const struct MTIM_Channel MTIM4_CH2_PD13;
extern const struct MTIM_Channel MTIM4_CH3_PB8;
extern const struct MTIM_Channel MTIM4_CH3_PD14;
extern const struct MTIM_Channel MTIM4_CH4_PB9;
extern const struct MTIM_Channel MTIM4_CH4_PD15;

#endif /* MTIM4_PRESENT */

#ifdef MTIM14_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM14;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM14_CH1;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM14_CH1_PA4;
extern const struct MTIM_Channel MTIM14_CH1_PA7;
extern const struct MTIM_Channel MTIM14_CH1_PB1;
extern const struct MTIM_Channel MTIM14_CH1_PC12;
extern const struct MTIM_Channel MTIM14_CH1_PF0;

#endif /* MTIM14_PRESENT */

#ifdef MTIM15_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM15;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM15_CH1;
extern const struct MTIM_Channel MTIM15_CH2;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM15_CH1_PA2;
extern const struct MTIM_Channel MTIM15_CH1_PB14;
extern const struct MTIM_Channel MTIM15_CH1_PC1;
extern const struct MTIM_Channel MTIM15_CH2_PA3;
extern const struct MTIM_Channel MTIM15_CH2_PB15;
extern const struct MTIM_Channel MTIM15_CH2_PC2;

#endif /* MTIM15_PRESENT */

#ifdef MTIM16_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM16;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM16_CH1;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM16_CH1_PA6;
extern const struct MTIM_Channel MTIM16_CH1_PB8;
extern const struct MTIM_Channel MTIM16_CH1_PD0;

#endif /* MTIM16_PRESENT */

#ifdef MTIM17_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM17;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM17_CH1;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM17_CH1_PA7;
extern const struct MTIM_Channel MTIM17_CH1_PB9;
extern const struct MTIM_Channel MTIM17_CH1_PD1;

#endif /* MTIM17_PRESENT */

#ifdef MTIMLP1_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIMLP1;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIMLP1_PB6;
extern const struct MTIM_Timer MTIMLP1_PC3;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIMLP1_OUT;
extern const struct MTIM_Channel MTIMLP1_IN1;
extern const struct MTIM_Channel MTIMLP1_IN2;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIMLP1_OUT_PA0;
extern const struct MTIM_Channel MTIMLP1_OUT_PB0;
extern const struct MTIM_Channel MTIMLP1_OUT_PB2;
extern const struct MTIM_Channel MTIMLP1_OUT_PC1;
extern const struct MTIM_Channel MTIMLP1_OUT_PD8;
extern const struct MTIM_Channel MTIMLP1_IN1_PB5;
extern const struct MTIM_Channel MTIMLP1_IN1_PC0;
extern const struct MTIM_Channel MTIMLP1_IN2_PB7;
extern const struct MTIM_Channel MTIMLP1_IN2_PC2;

#endif /* MTIMLP1_PRESENT */

#ifdef MTIMLP2_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIMLP2;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIMLP2_PA5;
extern const struct MTIM_Timer MTIMLP2_PC3;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIMLP2_OUT;
extern const struct MTIM_Channel MTIMLP2_IN1;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIMLP2_OUT_PA4;
extern const struct MTIM_Channel MTIMLP2_OUT_PA8;
extern const struct MTIM_Channel MTIMLP2_OUT_PD6;
extern const struct MTIM_Channel MTIMLP2_IN1_PB1;
extern const struct MTIM_Channel MTIMLP2_IN1_PC0;

#endif /* MTIMLP2_PRESENT */


#endif /* MCAL_MTIM_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MI2C                                         */
/******************************************************************************/

#ifdef MCAL_MI2C_INCLUDED
/* MI2C channels */
#ifdef MI2C1_PRESENT
extern const struct MI2C_Channel MI2C1_SDA_PA10_SCL_PA9;
extern const struct MI2C_Channel MI2C1_SDA_PA10_SCL_PB6;
extern const struct MI2C_Channel MI2C1_SDA_PA10_SCL_PB8;
extern const struct MI2C_Channel MI2C1_SDA_PB7_SCL_PA9;
extern const struct MI2C_Channel MI2C1_SDA_PB7_SCL_PB6;
extern const struct MI2C_Channel MI2C1_SDA_PB7_SCL_PB8;
extern const struct MI2C_Channel MI2C1_SDA_PB9_SCL_PA9;
extern const struct MI2C_Channel MI2C1_SDA_PB9_SCL_PB6;
extern const struct MI2C_Channel MI2C1_SDA_PB9_SCL_PB8;

#endif /* MI2C1_PRESENT */

#ifdef MI2C2_PRESENT
extern const struct MI2C_Channel MI2C2_SDA_PA6_SCL_PA7;
extern const struct MI2C_Channel MI2C2_SDA_PA6_SCL_PA9;
extern const struct MI2C_Channel MI2C2_SDA_PA6_SCL_PA11;
extern const struct MI2C_Channel MI2C2_SDA_PA6_SCL_PB3;
extern const struct MI2C_Channel MI2C2_SDA_PA6_SCL_PB10;
extern const struct MI2C_Channel MI2C2_SDA_PA6_SCL_PB13;
extern const struct MI2C_Channel MI2C2_SDA_PA10_SCL_PA7;
extern const struct MI2C_Channel MI2C2_SDA_PA10_SCL_PA9;
extern const struct MI2C_Channel MI2C2_SDA_PA10_SCL_PA11;
extern const struct MI2C_Channel MI2C2_SDA_PA10_SCL_PB3;
extern const struct MI2C_Channel MI2C2_SDA_PA10_SCL_PB10;
extern const struct MI2C_Channel MI2C2_SDA_PA10_SCL_PB13;
extern const struct MI2C_Channel MI2C2_SDA_PA12_SCL_PA7;
extern const struct MI2C_Channel MI2C2_SDA_PA12_SCL_PA9;
extern const struct MI2C_Channel MI2C2_SDA_PA12_SCL_PA11;
extern const struct MI2C_Channel MI2C2_SDA_PA12_SCL_PB3;
extern const struct MI2C_Channel MI2C2_SDA_PA12_SCL_PB10;
extern const struct MI2C_Channel MI2C2_SDA_PA12_SCL_PB13;
extern const struct MI2C_Channel MI2C2_SDA_PB4_SCL_PA7;
extern const struct MI2C_Channel MI2C2_SDA_PB4_SCL_PA9;
extern const struct MI2C_Channel MI2C2_SDA_PB4_SCL_PA11;
extern const struct MI2C_Channel MI2C2_SDA_PB4_SCL_PB3;
extern const struct MI2C_Channel MI2C2_SDA_PB4_SCL_PB10;
extern const struct MI2C_Channel MI2C2_SDA_PB4_SCL_PB13;
extern const struct MI2C_Channel MI2C2_SDA_PB11_SCL_PA7;
extern const struct MI2C_Channel MI2C2_SDA_PB11_SCL_PA9;
extern const struct MI2C_Channel MI2C2_SDA_PB11_SCL_PA11;
extern const struct MI2C_Channel MI2C2_SDA_PB11_SCL_PB3;
extern const struct MI2C_Channel MI2C2_SDA_PB11_SCL_PB10;
extern const struct MI2C_Channel MI2C2_SDA_PB11_SCL_PB13;
extern const struct MI2C_Channel MI2C2_SDA_PB14_SCL_PA7;
extern const struct MI2C_Channel MI2C2_SDA_PB14_SCL_PA9;
extern const struct MI2C_Channel MI2C2_SDA_PB14_SCL_PA11;
extern const struct MI2C_Channel MI2C2_SDA_PB14_SCL_PB3;
extern const struct MI2C_Channel MI2C2_SDA_PB14_SCL_PB10;
extern const struct MI2C_Channel MI2C2_SDA_PB14_SCL_PB13;

#endif /* MI2C2_PRESENT */

#ifdef MI2C3_PRESENT
extern const struct MI2C_Channel MI2C3_SDA_PA6_SCL_PA7;
extern const struct MI2C_Channel MI2C3_SDA_PA6_SCL_PB3;
extern const struct MI2C_Channel MI2C3_SDA_PA6_SCL_PC0;
extern const struct MI2C_Channel MI2C3_SDA_PB4_SCL_PA7;
extern const struct MI2C_Channel MI2C3_SDA_PB4_SCL_PB3;
extern const struct MI2C_Channel MI2C3_SDA_PB4_SCL_PC0;
extern const struct MI2C_Channel MI2C3_SDA_PC1_SCL_PA7;
extern const struct MI2C_Channel MI2C3_SDA_PC1_SCL_PB3;
extern const struct MI2C_Channel MI2C3_SDA_PC1_SCL_PC0;

#endif /* MI2C3_PRESENT */


#endif /* MCAL_MI2C_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MSPI                                          */
/******************************************************************************/

#ifdef MCAL_MSPI_INCLUDED
/* MSPI channels */
#ifdef MSPI1_PRESENT
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA6_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA6_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA6_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA6_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA6_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA11_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA11_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA11_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA11_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PA11_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PB4_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PB4_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PB4_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PB4_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PD5_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PD5_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PD5_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PD5_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA1_MISO_PD5_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA6_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA6_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA6_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA6_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA6_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA11_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA11_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA11_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA11_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PA11_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PB4_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PB4_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PB4_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PB4_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PD5_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PD5_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PD5_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PD5_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PA5_MISO_PD5_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA6_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA6_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA6_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA6_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA6_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA11_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA11_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA11_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA11_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PA11_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PB4_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PB4_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PB4_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PB4_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PD5_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PD5_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PD5_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PD5_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PB3_MISO_PD5_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA6_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA6_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA6_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA6_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA6_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA11_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA11_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA11_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA11_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PA11_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PB4_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PB4_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PB4_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PB4_MOSI_PD6;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PD5_MOSI_PA2;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PD5_MOSI_PA7;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PD5_MOSI_PA12;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PD5_MOSI_PB5;
extern const struct MSPI_Channel MSPI1_SCK_PD8_MISO_PD5_MOSI_PD6;

#endif /* MSPI1_PRESENT */

#ifdef MSPI2_PRESENT
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PA9_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB6_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PB14_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PC2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PA0_MISO_PD3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PA9_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB6_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PB14_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PC2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB8_MISO_PD3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PA9_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB6_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PB14_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PC2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB10_MISO_PD3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PA9_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB6_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PB14_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PC2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PB13_MISO_PD3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA3_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PA9_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB6_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PB14_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PC2_MOSI_PD4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PA4;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PA10;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PB7;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PB11;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PB15;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PC3;
extern const struct MSPI_Channel MSPI2_SCK_PD1_MISO_PD3_MOSI_PD4;

#endif /* MSPI2_PRESENT */

#ifdef MSPI3_PRESENT
extern const struct MSPI_Channel MSPI3_SCK_PB3_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI3_SCK_PB3_MISO_PB4_MOSI_PC12;
extern const struct MSPI_Channel MSPI3_SCK_PB3_MISO_PC11_MOSI_PB5;
extern const struct MSPI_Channel MSPI3_SCK_PB3_MISO_PC11_MOSI_PC12;
extern const struct MSPI_Channel MSPI3_SCK_PC10_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI3_SCK_PC10_MISO_PB4_MOSI_PC12;
extern const struct MSPI_Channel MSPI3_SCK_PC10_MISO_PC11_MOSI_PB5;
extern const struct MSPI_Channel MSPI3_SCK_PC10_MISO_PC11_MOSI_PC12;

#endif /* MSPI3_PRESENT */


#endif /* MCAL_MSPI_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MDAC                                          */
/******************************************************************************/

#ifdef MCAL_MDAC_INCLUDED
#ifdef MDAC_PRESENT
/* MDAC peripheral */
extern const struct MDAC_Periph MDAC1;

extern const struct MDAC_Channel MDAC1_OUT1_PA4;
extern const struct MDAC_Channel MDAC1_OUT2_PA5;

#endif /* MDAC_PRESENT */
#endif /* MCAL_MDAC_INCLUDED */

/*lint -restore -e1756 */

#ifdef __cplusplus
}
#endif

#endif // MCAL_CHANNELS_H
