/*******************************************************************************
 *  Copyright (c) 2025 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *   PROJECT          Generic SW
 *   COMP_ABBREV      INTP      
 ******************************************************************************/


/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file     IntPrioTbl_auto.c
 *
 *  \brief    Interrupt priority table
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */


/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/

#include "IntPrioTbl_auto.h"

/******************************************************************************/
/* PUBLIC DATA DEFINITIONS                                                    */
/******************************************************************************/

#ifdef INTP_CONFIG_ENABLED
const struct INTP_PrioConfig INTP_PrioTbl[] =
{
// No entries in JSON dict
};

const uint32_t INTP_PrioTblSize = 0UL;
#endif
