/*******************************************************************************
 *  Copyright (c) 2022 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          MCAL
 *  PROCESSOR        RA4
 ******************************************************************************/


#ifndef MCAL_CHANNELS_H
#define MCAL_CHANNELS_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file
 *
 *  \ingroup  MCAL
 *
 *  \brief    Public declarations of MCAL channels
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */


/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/

#include "BSH_stdinc.h"
#include "processor.h"
#include "features.h"
#include "mcal/mcal_includes.h"
#include "mcal/mcal.h"


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR USER CHANNELS                                 */
/******************************************************************************/

/* USER SECTION BEGIN USER_CHANNELS */

/* USER SECTION END */


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MDIO                                          */
/******************************************************************************/

/* MDIO channels without alternate function */
extern const struct MDIO_Channel MDIO000;
extern const struct MDIO_Channel MDIO001;
extern const struct MDIO_Channel MDIO002;
extern const struct MDIO_Channel MDIO003;
extern const struct MDIO_Channel MDIO004;
extern const struct MDIO_Channel MDIO005;
extern const struct MDIO_Channel MDIO006;
extern const struct MDIO_Channel MDIO007;
extern const struct MDIO_Channel MDIO008;
extern const struct MDIO_Channel MDIO013;
extern const struct MDIO_Channel MDIO014;
extern const struct MDIO_Channel MDIO015;
extern const struct MDIO_Channel MDIO100;
extern const struct MDIO_Channel MDIO101;
extern const struct MDIO_Channel MDIO102;
extern const struct MDIO_Channel MDIO103;
extern const struct MDIO_Channel MDIO104;
extern const struct MDIO_Channel MDIO105;
extern const struct MDIO_Channel MDIO106;
extern const struct MDIO_Channel MDIO107;
extern const struct MDIO_Channel MDIO108;
extern const struct MDIO_Channel MDIO109;
extern const struct MDIO_Channel MDIO110;
extern const struct MDIO_Channel MDIO111;
extern const struct MDIO_Channel MDIO112;
extern const struct MDIO_Channel MDIO113;
extern const struct MDIO_Channel MDIO114;
extern const struct MDIO_Channel MDIO115;
extern const struct MDIO_Channel MDIO200;
extern const struct MDIO_Channel MDIO201;
extern const struct MDIO_Channel MDIO205;
extern const struct MDIO_Channel MDIO206;
extern const struct MDIO_Channel MDIO207;
extern const struct MDIO_Channel MDIO208;
extern const struct MDIO_Channel MDIO209;
extern const struct MDIO_Channel MDIO210;
extern const struct MDIO_Channel MDIO211;
extern const struct MDIO_Channel MDIO212;
extern const struct MDIO_Channel MDIO213;
extern const struct MDIO_Channel MDIO214;
extern const struct MDIO_Channel MDIO300;
extern const struct MDIO_Channel MDIO301;
extern const struct MDIO_Channel MDIO302;
extern const struct MDIO_Channel MDIO303;
extern const struct MDIO_Channel MDIO304;
extern const struct MDIO_Channel MDIO305;
extern const struct MDIO_Channel MDIO306;
extern const struct MDIO_Channel MDIO307;
extern const struct MDIO_Channel MDIO400;
extern const struct MDIO_Channel MDIO401;
extern const struct MDIO_Channel MDIO402;
extern const struct MDIO_Channel MDIO403;
extern const struct MDIO_Channel MDIO404;
extern const struct MDIO_Channel MDIO405;
extern const struct MDIO_Channel MDIO406;
extern const struct MDIO_Channel MDIO407;
extern const struct MDIO_Channel MDIO408;
extern const struct MDIO_Channel MDIO409;
extern const struct MDIO_Channel MDIO410;
extern const struct MDIO_Channel MDIO411;
extern const struct MDIO_Channel MDIO412;
extern const struct MDIO_Channel MDIO413;
extern const struct MDIO_Channel MDIO414;
extern const struct MDIO_Channel MDIO415;
extern const struct MDIO_Channel MDIO500;
extern const struct MDIO_Channel MDIO501;
extern const struct MDIO_Channel MDIO502;
extern const struct MDIO_Channel MDIO503;
extern const struct MDIO_Channel MDIO504;
extern const struct MDIO_Channel MDIO505;
extern const struct MDIO_Channel MDIO600;
extern const struct MDIO_Channel MDIO601;
extern const struct MDIO_Channel MDIO602;
extern const struct MDIO_Channel MDIO603;
extern const struct MDIO_Channel MDIO608;
extern const struct MDIO_Channel MDIO609;
extern const struct MDIO_Channel MDIO610;
extern const struct MDIO_Channel MDIO708;

/* MDIO channels with alternate function */
extern const struct MDIO_Channel MDIO100_AGTIO0;
extern const struct MDIO_Channel MDIO100_GTETRGA;
extern const struct MDIO_Channel MDIO100_GTIOC5B;
extern const struct MDIO_Channel MDIO100_RXD0_MISO0_SCL0;
extern const struct MDIO_Channel MDIO100_SCK1;
extern const struct MDIO_Channel MDIO100_QSPCLK;
extern const struct MDIO_Channel MDIO101_AGTEE0;
extern const struct MDIO_Channel MDIO101_GTETRGB;
extern const struct MDIO_Channel MDIO101_GTIOC5A;
extern const struct MDIO_Channel MDIO101_TXD0_MOSI0_SDA0;
extern const struct MDIO_Channel MDIO101_CTS1RTS1_SS1;
extern const struct MDIO_Channel MDIO101_QIO1;
extern const struct MDIO_Channel MDIO102_AGTO0;
extern const struct MDIO_Channel MDIO102_GTOWLO;
extern const struct MDIO_Channel MDIO102_GTIOC2B;
extern const struct MDIO_Channel MDIO102_SCK0;
extern const struct MDIO_Channel MDIO102_ADTRG0;
extern const struct MDIO_Channel MDIO102_CRX0;
extern const struct MDIO_Channel MDIO102_QIO0;
extern const struct MDIO_Channel MDIO103_AGTIO2;
extern const struct MDIO_Channel MDIO103_GTOWUP;
extern const struct MDIO_Channel MDIO103_GTIOC2A;
extern const struct MDIO_Channel MDIO103_CTS0RTS0_SS0;
extern const struct MDIO_Channel MDIO103_CTX0;
extern const struct MDIO_Channel MDIO103_QIO3;
extern const struct MDIO_Channel MDIO104_AGTEE2;
extern const struct MDIO_Channel MDIO104_GTETRGB;
extern const struct MDIO_Channel MDIO104_GTIOC1B;
extern const struct MDIO_Channel MDIO104_QIO2;
extern const struct MDIO_Channel MDIO105_AGTO2;
extern const struct MDIO_Channel MDIO105_GTETRGA;
extern const struct MDIO_Channel MDIO105_GTIOC1A;
extern const struct MDIO_Channel MDIO106_AGTOB0;
extern const struct MDIO_Channel MDIO107_AGTOA0;
extern const struct MDIO_Channel MDIO108_AGTOA3;
extern const struct MDIO_Channel MDIO108_GTOULO;
extern const struct MDIO_Channel MDIO108_GTIOC0B;
extern const struct MDIO_Channel MDIO108_CTS9RTS9_SS9;
extern const struct MDIO_Channel MDIO108_SSLA0;
extern const struct MDIO_Channel MDIO109_AGTOB3;
extern const struct MDIO_Channel MDIO109_GTOVUP;
extern const struct MDIO_Channel MDIO109_GTIOC1A;
extern const struct MDIO_Channel MDIO109_TXD9_MOSI9_SDA9;
extern const struct MDIO_Channel MDIO109_MOSIA;
extern const struct MDIO_Channel MDIO109_CLKOUT;
extern const struct MDIO_Channel MDIO110_AGTEE3;
extern const struct MDIO_Channel MDIO110_GTOVLO;
extern const struct MDIO_Channel MDIO110_GTIOC1B;
extern const struct MDIO_Channel MDIO110_CTS2RTS2_SS2;
extern const struct MDIO_Channel MDIO110_RXD9_MISO9_SCL9;
extern const struct MDIO_Channel MDIO110_MISOA;
extern const struct MDIO_Channel MDIO111_AGTOA5;
extern const struct MDIO_Channel MDIO111_GTIOC3A;
extern const struct MDIO_Channel MDIO111_SCK2;
extern const struct MDIO_Channel MDIO111_SCK9;
extern const struct MDIO_Channel MDIO111_RSPCKA;
extern const struct MDIO_Channel MDIO112_AGTOB5;
extern const struct MDIO_Channel MDIO112_GTIOC3B;
extern const struct MDIO_Channel MDIO112_TXD2_MOSI2_SDA2_TXDX2_SIOX2;
extern const struct MDIO_Channel MDIO112_SCK1;
extern const struct MDIO_Channel MDIO112_SSLA0;
extern const struct MDIO_Channel MDIO112_QSSL;
extern const struct MDIO_Channel MDIO112_SSIBCK0_B;
extern const struct MDIO_Channel MDIO113_AGTEE5;
extern const struct MDIO_Channel MDIO113_GTIOC2A;
extern const struct MDIO_Channel MDIO113_RXD2_MISO2_SCL2_RXDX2;
extern const struct MDIO_Channel MDIO113_SSILRCK0_SSIFS0_B;
extern const struct MDIO_Channel MDIO114_AGTIO5;
extern const struct MDIO_Channel MDIO114_GTIOC2B;
extern const struct MDIO_Channel MDIO114_CTS9;
extern const struct MDIO_Channel MDIO114_SSIRXD0_B;
extern const struct MDIO_Channel MDIO115_GTIOC4A;
extern const struct MDIO_Channel MDIO115_SSITXD0_B;
extern const struct MDIO_Channel MDIO205_AGTO1;
extern const struct MDIO_Channel MDIO205_GTIV;
extern const struct MDIO_Channel MDIO205_GTIOC4A;
extern const struct MDIO_Channel MDIO205_TXD4_MOSI4_SDA4;
extern const struct MDIO_Channel MDIO205_CTS9RTS9_SS9;
extern const struct MDIO_Channel MDIO205_SCL1_B;
extern const struct MDIO_Channel MDIO205_CLKOUT;
extern const struct MDIO_Channel MDIO205_TS01;
extern const struct MDIO_Channel MDIO205_USB_OVRCURADS;
extern const struct MDIO_Channel MDIO205_SD0DAT3_A;
extern const struct MDIO_Channel MDIO206_GTIU;
extern const struct MDIO_Channel MDIO206_RXD4_MISO4_SCL4;
extern const struct MDIO_Channel MDIO206_CTS9;
extern const struct MDIO_Channel MDIO206_SDA1_B;
extern const struct MDIO_Channel MDIO206_TS02;
extern const struct MDIO_Channel MDIO206_USB_VBUSEN;
extern const struct MDIO_Channel MDIO206_SD0DAT2_A;
extern const struct MDIO_Channel MDIO207_TXD4_MOSI4_SDA4;
extern const struct MDIO_Channel MDIO207_TSCAP;
extern const struct MDIO_Channel MDIO207_QSSL;
extern const struct MDIO_Channel MDIO208_GTOVLO;
extern const struct MDIO_Channel MDIO208_QIO3;
extern const struct MDIO_Channel MDIO208_SD0DAT0_B;
extern const struct MDIO_Channel MDIO208_TDATA3;
extern const struct MDIO_Channel MDIO209_AGTEE5;
extern const struct MDIO_Channel MDIO209_GTOVUP;
extern const struct MDIO_Channel MDIO209_QIO2;
extern const struct MDIO_Channel MDIO209_SD0WP;
extern const struct MDIO_Channel MDIO209_TDATA2;
extern const struct MDIO_Channel MDIO210_AGTOB5;
extern const struct MDIO_Channel MDIO210_GTIW;
extern const struct MDIO_Channel MDIO210_QIO1;
extern const struct MDIO_Channel MDIO210_SD0CD;
extern const struct MDIO_Channel MDIO210_TDATA1;
extern const struct MDIO_Channel MDIO211_AGTOA5;
extern const struct MDIO_Channel MDIO211_GTIV;
extern const struct MDIO_Channel MDIO211_QIO0;
extern const struct MDIO_Channel MDIO211_SD0CMD_B;
extern const struct MDIO_Channel MDIO211_TDATA0;
extern const struct MDIO_Channel MDIO212_AGTEE1;
extern const struct MDIO_Channel MDIO212_GTETRGD;
extern const struct MDIO_Channel MDIO212_GTIOC0B;
extern const struct MDIO_Channel MDIO212_RXD1_MISO1_SCL1_RXDX1;
extern const struct MDIO_Channel MDIO213_AGTEE2;
extern const struct MDIO_Channel MDIO213_GTETRGC;
extern const struct MDIO_Channel MDIO213_GTIOC0A;
extern const struct MDIO_Channel MDIO213_TXD1_MOSI1_SDA1_TXDX1_SIOX1;
extern const struct MDIO_Channel MDIO214_AGTO5;
extern const struct MDIO_Channel MDIO214_GTIU;
extern const struct MDIO_Channel MDIO214_QSPCLK;
extern const struct MDIO_Channel MDIO214_SD0CLK_B;
extern const struct MDIO_Channel MDIO214_TCLK;
extern const struct MDIO_Channel MDIO300_GTOUUP;
extern const struct MDIO_Channel MDIO300_GTIOC0A;
extern const struct MDIO_Channel MDIO300_SSLA1;
extern const struct MDIO_Channel MDIO301_AGTIO0;
extern const struct MDIO_Channel MDIO301_GTOULO;
extern const struct MDIO_Channel MDIO301_GTIOC4B;
extern const struct MDIO_Channel MDIO301_RXD2_MISO2_SCL2_RXDX2;
extern const struct MDIO_Channel MDIO301_CTS9RTS9_SS9;
extern const struct MDIO_Channel MDIO301_SSLA2;
extern const struct MDIO_Channel MDIO302_GTOUUP;
extern const struct MDIO_Channel MDIO302_GTIOC4A;
extern const struct MDIO_Channel MDIO302_TXD2_MOSI2_SDA2_TXDX2_SIOX2;
extern const struct MDIO_Channel MDIO302_SSLA3;
extern const struct MDIO_Channel MDIO303_GTIOC7B;
extern const struct MDIO_Channel MDIO303_CTS9;
extern const struct MDIO_Channel MDIO304_AGTEE2;
extern const struct MDIO_Channel MDIO304_GTOWLO;
extern const struct MDIO_Channel MDIO304_GTIOC7A;
extern const struct MDIO_Channel MDIO305_AGTOB2;
extern const struct MDIO_Channel MDIO305_GTOWUP;
extern const struct MDIO_Channel MDIO305_QSPCLK;
extern const struct MDIO_Channel MDIO306_AGTOA2;
extern const struct MDIO_Channel MDIO306_GTOULO;
extern const struct MDIO_Channel MDIO306_QSSL;
extern const struct MDIO_Channel MDIO307_AGTEE4;
extern const struct MDIO_Channel MDIO307_GTOUUP;
extern const struct MDIO_Channel MDIO307_QIO0;
extern const struct MDIO_Channel MDIO400_AGTIO1;
extern const struct MDIO_Channel MDIO400_GTIOC6A;
extern const struct MDIO_Channel MDIO400_SCK4;
extern const struct MDIO_Channel MDIO400_SCL0_A;
extern const struct MDIO_Channel MDIO400_SSLA0;
extern const struct MDIO_Channel MDIO400_AUDIO_CLK;
extern const struct MDIO_Channel MDIO401_GTETRGA;
extern const struct MDIO_Channel MDIO401_GTIOC6B;
extern const struct MDIO_Channel MDIO401_CTS4RTS4_SS4;
extern const struct MDIO_Channel MDIO401_SDA0_A;
extern const struct MDIO_Channel MDIO401_CTX0;
extern const struct MDIO_Channel MDIO402_CTS4;
extern const struct MDIO_Channel MDIO402_CACREF;
extern const struct MDIO_Channel MDIO402_CRX0;
extern const struct MDIO_Channel MDIO402_AUDIO_CLK;
extern const struct MDIO_Channel MDIO403_GTIOC3A;
extern const struct MDIO_Channel MDIO403_SSIBCK0_A;
extern const struct MDIO_Channel MDIO404_GTIOC3B;
extern const struct MDIO_Channel MDIO404_SSILRCK0_SSIFS0_A;
extern const struct MDIO_Channel MDIO405_GTIOC1A;
extern const struct MDIO_Channel MDIO405_SSITXD0_A;
extern const struct MDIO_Channel MDIO406_AGTO5;
extern const struct MDIO_Channel MDIO406_GTIOC1B;
extern const struct MDIO_Channel MDIO406_SSIRXD0_A;
extern const struct MDIO_Channel MDIO407_AGTIO0;
extern const struct MDIO_Channel MDIO407_GTIOC6A;
extern const struct MDIO_Channel MDIO407_CTS4RTS4_SS4;
extern const struct MDIO_Channel MDIO407_SDA0_B;
extern const struct MDIO_Channel MDIO407_RTCOUT;
extern const struct MDIO_Channel MDIO407_TS03;
extern const struct MDIO_Channel MDIO407_USB_VBUS;
extern const struct MDIO_Channel MDIO408_AGTOB2;
extern const struct MDIO_Channel MDIO408_GTOWLO;
extern const struct MDIO_Channel MDIO408_GTIOC6B;
extern const struct MDIO_Channel MDIO408_CTS4;
extern const struct MDIO_Channel MDIO408_RXD3_MISO3_SCL3;
extern const struct MDIO_Channel MDIO408_SCL0_B;
extern const struct MDIO_Channel MDIO408_TS04;
extern const struct MDIO_Channel MDIO408_USB_ID;
extern const struct MDIO_Channel MDIO409_AGTOA2;
extern const struct MDIO_Channel MDIO409_GTOWUP;
extern const struct MDIO_Channel MDIO409_TXD3_MOSI3_SDA3;
extern const struct MDIO_Channel MDIO409_TS05;
extern const struct MDIO_Channel MDIO409_USB_EXICEN;
extern const struct MDIO_Channel MDIO410_AGTOB1;
extern const struct MDIO_Channel MDIO410_GTOVLO;
extern const struct MDIO_Channel MDIO410_RXD0_MISO0_SCL0;
extern const struct MDIO_Channel MDIO410_SCK3;
extern const struct MDIO_Channel MDIO410_TS06;
extern const struct MDIO_Channel MDIO410_SD0DAT1_A;
extern const struct MDIO_Channel MDIO411_AGTOA1;
extern const struct MDIO_Channel MDIO411_GTOVUP;
extern const struct MDIO_Channel MDIO411_TXD0_MOSI0_SDA0;
extern const struct MDIO_Channel MDIO411_CTS3RTS3_SS3;
extern const struct MDIO_Channel MDIO411_TS07;
extern const struct MDIO_Channel MDIO411_SD0DAT0_A;
extern const struct MDIO_Channel MDIO412_AGTEE1;
extern const struct MDIO_Channel MDIO412_GTOULO;
extern const struct MDIO_Channel MDIO412_SCK0;
extern const struct MDIO_Channel MDIO412_CTS3;
extern const struct MDIO_Channel MDIO412_TS08;
extern const struct MDIO_Channel MDIO412_SD0CMD_A;
extern const struct MDIO_Channel MDIO413_AGTEE3;
extern const struct MDIO_Channel MDIO413_GTOUUP;
extern const struct MDIO_Channel MDIO413_CTS0RTS0_SS0;
extern const struct MDIO_Channel MDIO413_TS09;
extern const struct MDIO_Channel MDIO413_SD0CLK_A;
extern const struct MDIO_Channel MDIO414_AGTIO5;
extern const struct MDIO_Channel MDIO414_GTIOC0B;
extern const struct MDIO_Channel MDIO414_CTS0;
extern const struct MDIO_Channel MDIO414_TS10;
extern const struct MDIO_Channel MDIO414_SD0WP;
extern const struct MDIO_Channel MDIO415_AGTIO4;
extern const struct MDIO_Channel MDIO415_GTIOC0A;
extern const struct MDIO_Channel MDIO415_TS11;
extern const struct MDIO_Channel MDIO415_USB_VBUSEN;
extern const struct MDIO_Channel MDIO415_SD0CD;
extern const struct MDIO_Channel MDIO500_AGTOA0;
extern const struct MDIO_Channel MDIO500_GTIU;
extern const struct MDIO_Channel MDIO500_CACREF;
extern const struct MDIO_Channel MDIO500_QSPCLK;
extern const struct MDIO_Channel MDIO500_USB_VBUSEN;
extern const struct MDIO_Channel MDIO501_AGTOB0;
extern const struct MDIO_Channel MDIO501_GTIV;
extern const struct MDIO_Channel MDIO501_QSSL;
extern const struct MDIO_Channel MDIO501_USB_OVRCURA;
extern const struct MDIO_Channel MDIO502_AGTOA2;
extern const struct MDIO_Channel MDIO502_GTIW;
extern const struct MDIO_Channel MDIO502_QIO0;
extern const struct MDIO_Channel MDIO502_USB_OVRCURB;
extern const struct MDIO_Channel MDIO503_AGTOB2;
extern const struct MDIO_Channel MDIO503_GTETRGC;
extern const struct MDIO_Channel MDIO503_QIO1;
extern const struct MDIO_Channel MDIO503_USB_EXICEN;
extern const struct MDIO_Channel MDIO504_AGTOA3;
extern const struct MDIO_Channel MDIO504_GTETRGD;
extern const struct MDIO_Channel MDIO504_QIO2;
extern const struct MDIO_Channel MDIO504_USB_ID;
extern const struct MDIO_Channel MDIO505_AGTOB3;
extern const struct MDIO_Channel MDIO505_QIO3;
extern const struct MDIO_Channel MDIO600_AGTIO3;
extern const struct MDIO_Channel MDIO600_GTIOC6B;
extern const struct MDIO_Channel MDIO600_SCK9;
extern const struct MDIO_Channel MDIO600_CLKOUT;
extern const struct MDIO_Channel MDIO600_CACREF;
extern const struct MDIO_Channel MDIO601_AGTEE3;
extern const struct MDIO_Channel MDIO601_GTIOC6A;
extern const struct MDIO_Channel MDIO601_RXD9_MISO9_SCL9;
extern const struct MDIO_Channel MDIO602_AGTO3;
extern const struct MDIO_Channel MDIO602_GTIOC7B;
extern const struct MDIO_Channel MDIO602_TXD9_MOSI9_SDA9;
extern const struct MDIO_Channel MDIO603_AGTIO4;
extern const struct MDIO_Channel MDIO603_GTIOC7A;
extern const struct MDIO_Channel MDIO603_CTS9RTS9_SS9;
extern const struct MDIO_Channel MDIO608_GTIOC4B;
extern const struct MDIO_Channel MDIO609_AGTO5;
extern const struct MDIO_Channel MDIO609_GTIOC5A;
extern const struct MDIO_Channel MDIO610_AGTO4;
extern const struct MDIO_Channel MDIO610_GTIOC5B;
extern const struct MDIO_Channel MDIO708_RXD1_MISO1_SCL1_RXDX1;
extern const struct MDIO_Channel MDIO708_CACREF;
extern const struct MDIO_Channel MDIO708_TS12;
extern const struct MDIO_Channel MDIO708_AUDIO_CLK;


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MEXTI                                         */
/******************************************************************************/

#ifdef MCAL_MEXTI_INCLUDED
/* MEXTI channels */
extern const struct MEXTI_Channel MEXTI000;
extern const struct MEXTI_Channel MEXTI001;
extern const struct MEXTI_Channel MEXTI002;
extern const struct MEXTI_Channel MEXTI004;
extern const struct MEXTI_Channel MEXTI005;
extern const struct MEXTI_Channel MEXTI006;
extern const struct MEXTI_Channel MEXTI008;
extern const struct MEXTI_Channel MEXTI015;
extern const struct MEXTI_Channel MEXTI100;
extern const struct MEXTI_Channel MEXTI101;
extern const struct MEXTI_Channel MEXTI104;
extern const struct MEXTI_Channel MEXTI105;
extern const struct MEXTI_Channel MEXTI110;
extern const struct MEXTI_Channel MEXTI111;
extern const struct MEXTI_Channel MEXTI205;
extern const struct MEXTI_Channel MEXTI206;
extern const struct MEXTI_Channel MEXTI212;
extern const struct MEXTI_Channel MEXTI213;
extern const struct MEXTI_Channel MEXTI301;
extern const struct MEXTI_Channel MEXTI302;
extern const struct MEXTI_Channel MEXTI304;
extern const struct MEXTI_Channel MEXTI305;
extern const struct MEXTI_Channel MEXTI400;
extern const struct MEXTI_Channel MEXTI401;
extern const struct MEXTI_Channel MEXTI402;
extern const struct MEXTI_Channel MEXTI403;
extern const struct MEXTI_Channel MEXTI404;
extern const struct MEXTI_Channel MEXTI408;
extern const struct MEXTI_Channel MEXTI409;
extern const struct MEXTI_Channel MEXTI410;
extern const struct MEXTI_Channel MEXTI411;
extern const struct MEXTI_Channel MEXTI414;
extern const struct MEXTI_Channel MEXTI415;
extern const struct MEXTI_Channel MEXTI501;
extern const struct MEXTI_Channel MEXTI502;
extern const struct MEXTI_Channel MEXTI505;
extern const struct MEXTI_Channel MEXTI708;

#endif /* MCAL_MEXTI_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MUART                                         */
/******************************************************************************/

#ifdef MCAL_MUART_INCLUDED
/* MUART channels */
#ifdef MUART0_PRESENT
extern const struct MUART_Channel MUART0_RX_P100_TX_P101;
extern const struct MUART_Channel MUART0_RX_P100_TX_P411;
extern const struct MUART_Channel MUART0_RX_P410_TX_P101;
extern const struct MUART_Channel MUART0_RX_P410_TX_P411;

#endif /* MUART0_PRESENT */
#ifdef MUART1_PRESENT
extern const struct MUART_Channel MUART1_RX_P212_TX_P213;
extern const struct MUART_Channel MUART1_RX_P708_TX_P213;

#endif /* MUART1_PRESENT */
#ifdef MUART2_PRESENT
extern const struct MUART_Channel MUART2_RX_P113_TX_P112;
extern const struct MUART_Channel MUART2_RX_P113_TX_P302;
extern const struct MUART_Channel MUART2_RX_P301_TX_P112;
extern const struct MUART_Channel MUART2_RX_P301_TX_P302;

#endif /* MUART2_PRESENT */
#ifdef MUART3_PRESENT
extern const struct MUART_Channel MUART3_RX_P408_TX_P409;

#endif /* MUART3_PRESENT */
#ifdef MUART4_PRESENT
extern const struct MUART_Channel MUART4_RX_P206_TX_P205;
extern const struct MUART_Channel MUART4_RX_P206_TX_P207;

#endif /* MUART4_PRESENT */
#ifdef MUART9_PRESENT
extern const struct MUART_Channel MUART9_RX_P110_TX_P109;
extern const struct MUART_Channel MUART9_RX_P110_TX_P602;
extern const struct MUART_Channel MUART9_RX_P601_TX_P109;
extern const struct MUART_Channel MUART9_RX_P601_TX_P602;

#endif /* MUART9_PRESENT */

#endif /* MCAL_MUART_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MTIM                                          */
/******************************************************************************/

#ifdef MCAL_MTIM_INCLUDED
#ifdef MTIM0_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM0;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM0_CH1;
extern const struct MTIM_Channel MTIM0_CH2;
extern const struct MTIM_Channel MTIM0_CH3;
extern const struct MTIM_Channel MTIM0_CH4;
extern const struct MTIM_Channel MTIM0_CH5;
extern const struct MTIM_Channel MTIM0_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM0_CH1_P213;
extern const struct MTIM_Channel MTIM0_CH1_P300;
extern const struct MTIM_Channel MTIM0_CH1_P415;
extern const struct MTIM_Channel MTIM0_CH2_P108;
extern const struct MTIM_Channel MTIM0_CH2_P212;
extern const struct MTIM_Channel MTIM0_CH2_P414;

#endif /* MTIM0_PRESENT */

#ifdef MTIM1_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM1;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM1_CH1;
extern const struct MTIM_Channel MTIM1_CH2;
extern const struct MTIM_Channel MTIM1_CH3;
extern const struct MTIM_Channel MTIM1_CH4;
extern const struct MTIM_Channel MTIM1_CH5;
extern const struct MTIM_Channel MTIM1_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM1_CH1_P105;
extern const struct MTIM_Channel MTIM1_CH1_P109;
extern const struct MTIM_Channel MTIM1_CH1_P405;
extern const struct MTIM_Channel MTIM1_CH2_P104;
extern const struct MTIM_Channel MTIM1_CH2_P110;
extern const struct MTIM_Channel MTIM1_CH2_P406;

#endif /* MTIM1_PRESENT */

#ifdef MTIM2_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM2;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM2_CH1;
extern const struct MTIM_Channel MTIM2_CH2;
extern const struct MTIM_Channel MTIM2_CH3;
extern const struct MTIM_Channel MTIM2_CH4;
extern const struct MTIM_Channel MTIM2_CH5;
extern const struct MTIM_Channel MTIM2_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM2_CH1_P103;
extern const struct MTIM_Channel MTIM2_CH1_P113;
extern const struct MTIM_Channel MTIM2_CH2_P102;
extern const struct MTIM_Channel MTIM2_CH2_P114;

#endif /* MTIM2_PRESENT */

#ifdef MTIM3_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM3;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM3_CH1;
extern const struct MTIM_Channel MTIM3_CH2;
extern const struct MTIM_Channel MTIM3_CH3;
extern const struct MTIM_Channel MTIM3_CH4;
extern const struct MTIM_Channel MTIM3_CH5;
extern const struct MTIM_Channel MTIM3_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM3_CH1_P111;
extern const struct MTIM_Channel MTIM3_CH1_P403;
extern const struct MTIM_Channel MTIM3_CH2_P112;
extern const struct MTIM_Channel MTIM3_CH2_P404;

#endif /* MTIM3_PRESENT */

#ifdef MTIM4_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM4;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM4_CH1;
extern const struct MTIM_Channel MTIM4_CH2;
extern const struct MTIM_Channel MTIM4_CH3;
extern const struct MTIM_Channel MTIM4_CH4;
extern const struct MTIM_Channel MTIM4_CH5;
extern const struct MTIM_Channel MTIM4_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM4_CH1_P115;
extern const struct MTIM_Channel MTIM4_CH1_P205;
extern const struct MTIM_Channel MTIM4_CH1_P302;
extern const struct MTIM_Channel MTIM4_CH2_P301;
extern const struct MTIM_Channel MTIM4_CH2_P608;

#endif /* MTIM4_PRESENT */

#ifdef MTIM5_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM5;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM5_CH1;
extern const struct MTIM_Channel MTIM5_CH2;
extern const struct MTIM_Channel MTIM5_CH3;
extern const struct MTIM_Channel MTIM5_CH4;
extern const struct MTIM_Channel MTIM5_CH5;
extern const struct MTIM_Channel MTIM5_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM5_CH1_P101;
extern const struct MTIM_Channel MTIM5_CH1_P609;
extern const struct MTIM_Channel MTIM5_CH2_P100;
extern const struct MTIM_Channel MTIM5_CH2_P610;

#endif /* MTIM5_PRESENT */

#ifdef MTIM6_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM6;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM6_CH1;
extern const struct MTIM_Channel MTIM6_CH2;
extern const struct MTIM_Channel MTIM6_CH3;
extern const struct MTIM_Channel MTIM6_CH4;
extern const struct MTIM_Channel MTIM6_CH5;
extern const struct MTIM_Channel MTIM6_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM6_CH1_P400;
extern const struct MTIM_Channel MTIM6_CH1_P407;
extern const struct MTIM_Channel MTIM6_CH1_P601;
extern const struct MTIM_Channel MTIM6_CH2_P401;
extern const struct MTIM_Channel MTIM6_CH2_P408;
extern const struct MTIM_Channel MTIM6_CH2_P600;

#endif /* MTIM6_PRESENT */

#ifdef MTIM7_PRESENT
/* MTIM timer */
extern const struct MTIM_Timer MTIM7;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM7_CH1;
extern const struct MTIM_Channel MTIM7_CH2;
extern const struct MTIM_Channel MTIM7_CH3;
extern const struct MTIM_Channel MTIM7_CH4;
extern const struct MTIM_Channel MTIM7_CH5;
extern const struct MTIM_Channel MTIM7_CH6;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM7_CH1_P304;
extern const struct MTIM_Channel MTIM7_CH1_P603;
extern const struct MTIM_Channel MTIM7_CH2_P303;
extern const struct MTIM_Channel MTIM7_CH2_P602;

#endif /* MTIM7_PRESENT */


#endif /* MCAL_MTIM_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MADC                                          */
/******************************************************************************/

#ifdef MCAL_MADC_INCLUDED
/* MADC peripherals */
extern const struct MADC_Periph MADC0;

/* MADC peripheral with HW trigger */
extern const struct MADC_Periph MADC0_TRIG_A_GPT0_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT0_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT1_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT1_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT2_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT2_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT3_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT3_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT4_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT4_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT5_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT5_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT6_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT6_COUNTER_UNDERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT7_COUNTER_OVERFLOW;
extern const struct MADC_Periph MADC0_TRIG_A_GPT7_COUNTER_UNDERFLOW;

/* MADC channels */
extern const struct MADC_Channel MADC0_AN000_P000;
extern const struct MADC_Channel MADC0_AN001_P001;
extern const struct MADC_Channel MADC0_AN002_P002;
extern const struct MADC_Channel MADC0_AN003_P003;
extern const struct MADC_Channel MADC0_AN004_P004;
extern const struct MADC_Channel MADC0_AN005_P005;
extern const struct MADC_Channel MADC0_AN006_P006;
extern const struct MADC_Channel MADC0_AN007_P007;
extern const struct MADC_Channel MADC0_AN008_P008;
extern const struct MADC_Channel MADC0_AN011_P013;
extern const struct MADC_Channel MADC0_AN012_P014;
extern const struct MADC_Channel MADC0_AN013_P015;
extern const struct MADC_Channel MADC0_AN016_P500;

#endif /* MCAL_MADC_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MI2C                                         */
/******************************************************************************/

#ifdef MCAL_MI2C_INCLUDED
/* MI2C channels */
#endif /* MCAL_MI2C_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MSPI                                         */
/******************************************************************************/

#ifdef MCAL_MSPI_INCLUDED
/* MSPI channels */
#endif /* MCAL_MSPI_INCLUDED */


#ifdef __cplusplus
}
#endif

#endif // MCAL_CHANNELS_H
