
/**************************************************************************************************/
/* uVision template file                                                                         */
/**************************************************************************************************/

/**************************************************************************************************/
/* Reference to ELF-file                                                                          */
/**************************************************************************************************/
LOAD ELF_LOCATION NOCODE

/**************************************************************************************************/
/* LOCAL FUNCTIONS                                                                                */
/**************************************************************************************************/
#if defined(RTOS_TRACING_ENABLED) && !defined(RTOS_TRACING_MODE_STREAMING)
FUNC void SaveTraceData(void)
{
    printf("\nRTOS snapshot tracing info:\n");
    printf(  "------------------\n");
    printf("Saving trace data in RTOS_trace_data.hex!\n");
    printf("RTOS_trcBuf: 0x%x - 0x%x\n", &RTOS_traceBuffer, (&RTOS_traceBuffer+0x1));
    exec("SAVE \"./traces/RTOS_trace_data.hex\" &RTOS_traceBuffer , (&RTOS_traceBuffer+0x1)");
}
#else
printf("Info: To enable RTOS snapshot tracing set os_tracing_enable to TRUE and os_tracing_mode_streaming fo FALSE (@rtos_setup.mak)."); 
#endif

/**************************************************************************************************/
/* BUTTON DEFINITIONS                                                                             */
/**************************************************************************************************/
#if defined(RTOS_TRACING_ENABLED) && !defined(RTOS_TRACING_MODE_STREAMING)
DEFINE BUTTON "Save Trace Data", "SaveTraceData()"
#endif

