/*******************************************************************************
 *  Copyright (c) 2017 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  VARIANT          MYVARIANT
 ******************************************************************************/

#ifndef MYVARIANT_H
#define MYVARIANT_H

#define CRC32_SIZE	UINT32_C(0x4)
#define STACK_MAGIC_SIZE	UINT32_C(0x4)
#define APP_VARIANT
#define UC_VENDOR	GD
#define PROC_FAMILY	GD32F30X
#define GD32_ARM
#define GD32F30
#define GD32F30X_HD
#define GD32F303
#define GD32F303C
#define GD32F303CB
#define RESET_VECTOR	0x8000004
#define RAM0START	0x20000000UL
#define RAM0TOP	0x20007FFFUL
#define ROM1START	0x8002000UL
#define ROM1END	0x801FFFFUL
#define FLASH_SIZE	128UL
#define SSB_SHARED_SPI_USED
#define SSB_USE_CPP_INSTEAD_OF_C_API
#define SSBD_INCLUDED
#define DBAL_MAIN_CONNECTION_ADDRESS	0xC0
#define SRV_MEM_DYNAMIC_MEMORY_SIZE	0x10
#define BSP_DRV_MDMA_VARIANT	2
#define I2C_BY_MCAL
#define MCAL_INCLUDED
#define MCAL_MDIO_INCLUDED
#define MCAL_MUART_INCLUDED
#define MCAL_MEXTI_INCLUDED
#define MCAL_MPCM_INCLUDED
#define MCAL_MADC_INCLUDED
#define MCAL_MTIM_INCLUDED
#define MCAL_MWDT_INCLUDED
#define MCAL_MI2C_INCLUDED
#define MCAL_MSPI_INCLUDED
#define MCAL_MCOM_INCLUDED
#define MCAL_MDMA_INCLUDED
#define MSPI_MDMA_SUPPORTED
#define MCAL_MSUP_INCLUDED
#define DBM_MCAL
#define __MESSAGE_INPUT_BUFFER_SIZE	50U
#define DLL_TRANSMIT_BUFFER_DATA_LENGTH	85U
#define DBUS2_NODE_ID	Variant_MyVariant
#define __DBUS_NODE_ADDRESS	1
#define __TESTMSGSRV_SUBNODE_ADDRESS	10
#define DBUS2_INCLUDED
#define DBUS2_CONTROLLER_SPECIFIC_MAPPING
#define DBM_DERIVATIVE_SPECIFIC_ERROR_TYPE	uint16_t
#define DBUS_UART_CHANNEL	1
#define DBUS_UART_CHANNEL_1
#define __BIT_TIME	104u
#define SYSTEM_TIMER_PERIOD	1U
#define SYSTEM_TIMER_ENABLED
#define SYSTEM_TIMER_SYSTICK
#define WATCHDOG_INCLUDED
#define MAL_RELEASE_KEY_DEF	0x5E
#define MAL_DEVELOP_KEY_DEF	0xDE
#define MAL_ENABLE_DEF	0xEA
#define MAL_IGNORE_ERROR_DEF	0x1E
#define MAL_DISABLE_CALC_DEF	0xDC
#define MAL_RESERVED_DEF	0xFF
#define STACK_MONITOR_ENABLED
#define DBGX_INCLUDED
#define SCHEDULER
#define SCHEDULER_CONFIG_AUTO
#define DBAL_INCLUDED
#define BL_APPLICATION_ROM_START	UINT32_C(0x8002000)
#define FWU_ROMLOADER_START_ADDRESS	UINT32_C(0x8000000)
#define FWU_ROMLOADER_END_ADDRESS	UINT32_C(0x8001fff)
#define FWU_ROMLOADER_SIZE	UINT32_C(0x2000)
#define FWU_APPLICATION_START_ADDRESS	UINT32_C(0x8002000)
#define FWU_APPLICATION_END_ADDRESS	UINT32_C(0x801ffff)
#define FWU_APPLICATION_SIZE	UINT32_C(0x1e000)
#define BBL_SERVICES_INCLUDED
#define BBL_SRV_UTIL_INCLUDED
#define BBL_CML_INCLUDED
#define BBL_SRV_ETL_INCLUDED
#define BBL_GENERIC_INCLUDED
#define BBL_MEM_INCLUDED
#define BBL_PIN_INCLUDED
#define BBL_BSP_DRV_INCLUDED
#define BBL_BSP_UTILS_INCLUDED
#define RAM1_PHY_START	UINT32_C(0x20000000)
#define RAM1_PHY_END	UINT32_C(0x20007FFF)
#define RAM1_PHY_SIZE	UINT32_C(0x8000)
#define ROM1_PHY_START	UINT32_C(0x8000000)
#define ROM1_PHY_END	UINT32_C(0x801FFFF)
#define ROM3_PHY_START	UINT32_C(0x1FFFF800)
#define ROM3_PHY_END	UINT32_C(0x1FFFF80F)
#define ROM3_PHY_SIZE	UINT32_C(0x10)
#define ROM1_START	UINT32_C(0x8002000)
#define ROM1_END	UINT32_C(0x801FFFF)
#define ROM1_SIZE	UINT32_C(0x1E000)
#define ROM3_START	UINT32_C(0x1FFFF800)
#define ROM3_END	UINT32_C(0x1FFFF80F)
#define ROM3_SIZE	UINT32_C(0x10)
#define RAM1_START	UINT32_C(0x20000000)
#define RAM1_END	UINT32_C(0x20007FFF)
#define RAM1_SIZE	UINT32_C(0x8000)
#define PAGE_SIZE	UINT32_C(0x800)
#define HEAPSIZE	UINT32_C(0x10)
#define STACKSIZE	UINT32_C(0x400)
#define FWU_SHARED_DATA_SIZE	UINT32_C(0x40)
#define UNINIT_DATA_SIZE	UINT32_C(0x40)
#define RAMCONT_EXCLUDED_DATA_SIZE	UINT32_C(0x0)
#define CORE_CLOCK	120U
#define CORE_CLOCK_120M
#define PCLOCK1	60U
#define PCLOCK2	120U
#define EXT_CRYSTAL_OSC	8U
#define VTOR_ALIGN	UINT32_C(0x200)
#define VECTOR_TABLE_SIZE	UINT32_C(0x150)
#define FLASH_DRIVER_SIZE	UINT32_C(0x1B0)
#define DEBUG	0x00U
#define need_fixed_vectors
#define DBUS_DEFAULT_BAUDRATE	96U
#define HUART1_USED
#define GD32F303CBT6
#define MIN_WRITEBLOCK_SIZE	UINT32_C(0x2)
#define WIRED_FIRMWARE_UPDATE
#define CORTEX_M4
#define CORTEX_M4F
#define ALIGNMENT	4
#define __LITTLE_ENDIAN_ADAPTATION
#define ROOT_REGION	UINT32_C(0x8000000)
#define ARM_HW_FPU_PRESENT
#define TRASH_AREA_START	0x1000000
#define RELOC_ADDR	0x0
#define ANY_CONTINGENCY	0x50
#define UID	UINT64_C(12345)
#define VERSION_MAJOR	UINT16_C(1)
#define VERSION_MINOR	UINT16_C(2)
#define VERSION_REVISION	UINT16_C(3)
#define DBUS_TARGET_NODE	16
#define MCU_FW_VERSION_NUMBER	12000
#define MCU_FW_VERSION_MAJOR	1
#define MCU_FW_VERSION_MINOR	20
#define MCU_FW_VERSION_REVISION	0

#endif /* MYVARIANT_H */
