/*******************************************************************************
 *  Copyright (c) 2022 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          Smart Sensor Bus
 *  COMP_ABBREV      SSB_CFG
 ******************************************************************************/

#ifndef SSB_CONFIG_AUTO_H
#define SSB_CONFIG_AUTO_H

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file     ssb_config_auto.h
 *
 *  \ingroup  sbus_abstraction/constellation
 *
 *  \brief    Interfacing to the class containing the configurations done by
 *            the SSB-Configurator
 *
 *  \details  - This file has to be generated by the backend of the \n
 *              SSB-Configurator \n
 *            - The available file from the repository can be seen as an \n
 *              example for having an initial configuration not fitting to \n
 *              the special appliance prject
 */

/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/
extern "C" {

#include "bsh_stdinc.h"
#include "debug_mapping.h"
}

#include "constellation/hub.h"
#include "ssbf_mngr_common.h"

/******************************************************************************/
/* PREPROCESSOR DEFINITIONS                                                   */
/******************************************************************************/

#define SSB_MAX_NUMBER_OF_CLIENTS             ((uint8_t)4U)
#define SSB_NUMBER_OF_CONFIGURATION_BYTES     ((uint16_t)370U)

#define SSB_CFG_IDX                           ((uint16_t)0x3311U)
#define SSB_I2C_ADDR_OFFSETS_DEFAULT          ((uint8_t)0xE4)
#define SSB_CFG_TO_BE_LOADED                  ((uint8_t)0x01)

/******************************************************************************/
/* CLASS-IF DEFINITION                                                        */
/******************************************************************************/
namespace SSBAL
{
    namespace SSBCO
    {
        class SsbConfigurations_c
        {
        private:

        public:
            /** \brief  Contains the configuration data automatically generated \n
            *           by the SSB-Configurator to be loaded into the SSB-nodes
            *
            *   \details
            *   - The SSB-Configurator generates this file ssb_configurations \n
            *     completely.
            *   - The configuration data are inherited by class HubMngr_c. \n
            *   - The configuration data in this array here contain the \n
            *     configurations of all Hubs, that means of all instances of \n
            *     HubMngr_c and of Hub_c.
            *   - The first object of HubMngr_c sets the configuration data \n
            *     in Hub_c by referencing pointer.
            */
            static const uint8_t SsbConfigurationBytes[SSB_NUMBER_OF_CONFIGURATION_BYTES];

            /** \brief  Contains the values of explicite configuration variables \n
            *           generated by the SSB-Configurator
            */
            static const struct SsbExplictiteConfigurationParameters_s SsbExplictiteConfigurationParameters[SSB_MAX_NUMBER_OF_CLIENTS];
        };
    }
}

#endif // From: #ifndef SSB_CONFIG_AUTO_H

