/*******************************************************************************
 *  Copyright (c) 2023 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          MCAL
 *  PROCESSOR        GD32F30x
 ******************************************************************************/

// Axivion Disable Style MisraC2012-8.9: Global variable can be declared inside function

#ifndef MCAL_CHANNELS_H
#define MCAL_CHANNELS_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file     mcal_channels.h
 *
 *  \ingroup  MCAL
 *
 *  \brief    Public declarations of MCAL channels
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */


/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/

#include "BSH_stdinc.h"
#include "processor.h"
#include "features.h"
#include "mcal/mcal_includes.h"
#include "mcal/mcal.h"


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MDIO                                          */
/******************************************************************************/

/* MDIO channels without alternate function */
extern const struct MDIO_Channel MDIOA0;
extern const struct MDIO_Channel MDIOA1;
extern const struct MDIO_Channel MDIOA2;
extern const struct MDIO_Channel MDIOA3;
extern const struct MDIO_Channel MDIOA4;
extern const struct MDIO_Channel MDIOA5;
extern const struct MDIO_Channel MDIOA6;
extern const struct MDIO_Channel MDIOA7;
extern const struct MDIO_Channel MDIOA8;
extern const struct MDIO_Channel MDIOA9;
extern const struct MDIO_Channel MDIOA10;
extern const struct MDIO_Channel MDIOA11;
extern const struct MDIO_Channel MDIOA12;
extern const struct MDIO_Channel MDIOA13;
extern const struct MDIO_Channel MDIOA14;
extern const struct MDIO_Channel MDIOA15;
extern const struct MDIO_Channel MDIOB0;
extern const struct MDIO_Channel MDIOB1;
extern const struct MDIO_Channel MDIOB2;
extern const struct MDIO_Channel MDIOB3;
extern const struct MDIO_Channel MDIOB4;
extern const struct MDIO_Channel MDIOB5;
extern const struct MDIO_Channel MDIOB6;
extern const struct MDIO_Channel MDIOB7;
extern const struct MDIO_Channel MDIOB8;
extern const struct MDIO_Channel MDIOB9;
extern const struct MDIO_Channel MDIOB10;
extern const struct MDIO_Channel MDIOB11;
extern const struct MDIO_Channel MDIOB12;
extern const struct MDIO_Channel MDIOB13;
extern const struct MDIO_Channel MDIOB14;
extern const struct MDIO_Channel MDIOB15;
extern const struct MDIO_Channel MDIOC0;
extern const struct MDIO_Channel MDIOC1;
extern const struct MDIO_Channel MDIOC2;
extern const struct MDIO_Channel MDIOC3;
extern const struct MDIO_Channel MDIOC4;
extern const struct MDIO_Channel MDIOC5;
extern const struct MDIO_Channel MDIOC6;
extern const struct MDIO_Channel MDIOC7;
extern const struct MDIO_Channel MDIOC8;
extern const struct MDIO_Channel MDIOC9;
extern const struct MDIO_Channel MDIOC10;
extern const struct MDIO_Channel MDIOC11;
extern const struct MDIO_Channel MDIOC12;
extern const struct MDIO_Channel MDIOC13;
extern const struct MDIO_Channel MDIOC14;
extern const struct MDIO_Channel MDIOC15;
extern const struct MDIO_Channel MDIOD0;
extern const struct MDIO_Channel MDIOD1;
extern const struct MDIO_Channel MDIOD2;

/* MDIO channels with alternate function */
extern const struct MDIO_Channel MDIOA0_MTIM1_CH0;
extern const struct MDIO_Channel MDIOA0_MTIM1_ETI;
extern const struct MDIO_Channel MDIOA0_MTIM4_CH0;
extern const struct MDIO_Channel MDIOA0_MTIM7_ETI;
extern const struct MDIO_Channel MDIOA1_MTIM1_CH1;
extern const struct MDIO_Channel MDIOA1_MTIM4_CH1;
extern const struct MDIO_Channel MDIOA2_MUART1_TX;
extern const struct MDIO_Channel MDIOA2_MTIM1_CH2;
extern const struct MDIO_Channel MDIOA2_MTIM4_CH2;
extern const struct MDIO_Channel MDIOA3_MUART1_RX;
extern const struct MDIO_Channel MDIOA3_MTIM1_CH3;
extern const struct MDIO_Channel MDIOA3_MTIM4_CH3;
extern const struct MDIO_Channel MDIOA4_MSPI0_NSS;
extern const struct MDIO_Channel MDIOA4_MSPI2_NSS;
extern const struct MDIO_Channel MDIOA5_MSPI0_SCK;
extern const struct MDIO_Channel MDIOA6_MSPI0_MISO;
extern const struct MDIO_Channel MDIOA6_MTIM2_CH0;
extern const struct MDIO_Channel MDIOA7_MSPI0_MOSI;
extern const struct MDIO_Channel MDIOA7_MTIM2_CH1;
extern const struct MDIO_Channel MDIOA8_MTIM0_CH0;
extern const struct MDIO_Channel MDIOA8_CK_OUT;
extern const struct MDIO_Channel MDIOA9_MUART0_TX;
extern const struct MDIO_Channel MDIOA9_MTIM0_CH1;
extern const struct MDIO_Channel MDIOA10_MUART0_RX;
extern const struct MDIO_Channel MDIOA10_MTIM0_CH2;
extern const struct MDIO_Channel MDIOA11_MTIM0_CH3;
extern const struct MDIO_Channel MDIOA12_MTIM0_ETI;
extern const struct MDIO_Channel MDIOA15_MSPI2_NSS;
extern const struct MDIO_Channel MDIOA15_MTIM1_CH0;
extern const struct MDIO_Channel MDIOA15_MTIM1_ETI;
extern const struct MDIO_Channel MDIOA15_MSPI0_NSS;
extern const struct MDIO_Channel MDIOB0_MTIM2_CH2;
extern const struct MDIO_Channel MDIOB1_MTIM2_CH3;
extern const struct MDIO_Channel MDIOB3_MSPI2_SCK;
extern const struct MDIO_Channel MDIOB3_MTIM1_CH1;
extern const struct MDIO_Channel MDIOB3_MSPI0_SCK;
extern const struct MDIO_Channel MDIOB4_MSPI2_MISO;
extern const struct MDIO_Channel MDIOB4_MTIM2_CH0;
extern const struct MDIO_Channel MDIOB4_MSPI0_MISO;
extern const struct MDIO_Channel MDIOB5_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOB5_MTIM2_CH1;
extern const struct MDIO_Channel MDIOB5_MSPI0_MOSI;
extern const struct MDIO_Channel MDIOB6_MI2C0_SCL;
extern const struct MDIO_Channel MDIOB6_MTIM3_CH0;
extern const struct MDIO_Channel MDIOB6_MUART0_TX;
extern const struct MDIO_Channel MDIOB7_MI2C0_SDA;
extern const struct MDIO_Channel MDIOB7_MTIM3_CH1;
extern const struct MDIO_Channel MDIOB7_MUART0_RX;
extern const struct MDIO_Channel MDIOB8_MTIM3_CH2;
extern const struct MDIO_Channel MDIOB8_MI2C0_SCL;
extern const struct MDIO_Channel MDIOB9_MTIM3_CH3;
extern const struct MDIO_Channel MDIOB9_MI2C0_SDA;
extern const struct MDIO_Channel MDIOB10_MI2C1_SCL;
extern const struct MDIO_Channel MDIOB10_MUART2_TX;
extern const struct MDIO_Channel MDIOB10_MTIM1_CH2;
extern const struct MDIO_Channel MDIOB11_MI2C1_SDA;
extern const struct MDIO_Channel MDIOB11_MUART2_RX;
extern const struct MDIO_Channel MDIOB11_MTIM1_CH3;
extern const struct MDIO_Channel MDIOB12_MSPI1_NSS;
extern const struct MDIO_Channel MDIOB13_MSPI1_SCK;
extern const struct MDIO_Channel MDIOB14_MSPI1_MISO;
extern const struct MDIO_Channel MDIOB15_MSPI1_MOSI;
extern const struct MDIO_Channel MDIOC6_MTIM7_CH0;
extern const struct MDIO_Channel MDIOC6_MTIM2_CH0;
extern const struct MDIO_Channel MDIOC7_MTIM7_CH1;
extern const struct MDIO_Channel MDIOC7_MTIM2_CH1;
extern const struct MDIO_Channel MDIOC8_MTIM7_CH2;
extern const struct MDIO_Channel MDIOC8_MTIM2_CH2;
extern const struct MDIO_Channel MDIOC9_MTIM7_CH3;
extern const struct MDIO_Channel MDIOC9_MTIM2_CH3;
extern const struct MDIO_Channel MDIOC10_MUART3_TX;
extern const struct MDIO_Channel MDIOC10_MUART2_TX;
extern const struct MDIO_Channel MDIOC10_MSPI2_SCK;
extern const struct MDIO_Channel MDIOC11_MUART3_RX;
extern const struct MDIO_Channel MDIOC11_MUART2_RX;
extern const struct MDIO_Channel MDIOC11_MSPI2_MISO;
extern const struct MDIO_Channel MDIOC12_MUART4_TX;
extern const struct MDIO_Channel MDIOC12_MSPI2_MOSI;
extern const struct MDIO_Channel MDIOD2_MTIM2_ETI;
extern const struct MDIO_Channel MDIOD2_MUART4_RX;


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MEXTI                                         */
/******************************************************************************/

#ifdef MCAL_MEXTI_INCLUDED
/* MEXTI channels without alternate function */
extern const struct MEXTI_Channel MEXTIA0;
extern const struct MEXTI_Channel MEXTIA1;
extern const struct MEXTI_Channel MEXTIA2;
extern const struct MEXTI_Channel MEXTIA3;
extern const struct MEXTI_Channel MEXTIA4;
extern const struct MEXTI_Channel MEXTIA5;
extern const struct MEXTI_Channel MEXTIA6;
extern const struct MEXTI_Channel MEXTIA7;
extern const struct MEXTI_Channel MEXTIA8;
extern const struct MEXTI_Channel MEXTIA9;
extern const struct MEXTI_Channel MEXTIA10;
extern const struct MEXTI_Channel MEXTIA11;
extern const struct MEXTI_Channel MEXTIA12;
extern const struct MEXTI_Channel MEXTIA13;
extern const struct MEXTI_Channel MEXTIA14;
extern const struct MEXTI_Channel MEXTIA15;
extern const struct MEXTI_Channel MEXTIB0;
extern const struct MEXTI_Channel MEXTIB1;
extern const struct MEXTI_Channel MEXTIB2;
extern const struct MEXTI_Channel MEXTIB3;
extern const struct MEXTI_Channel MEXTIB4;
extern const struct MEXTI_Channel MEXTIB5;
extern const struct MEXTI_Channel MEXTIB6;
extern const struct MEXTI_Channel MEXTIB7;
extern const struct MEXTI_Channel MEXTIB8;
extern const struct MEXTI_Channel MEXTIB9;
extern const struct MEXTI_Channel MEXTIB10;
extern const struct MEXTI_Channel MEXTIB11;
extern const struct MEXTI_Channel MEXTIB12;
extern const struct MEXTI_Channel MEXTIB13;
extern const struct MEXTI_Channel MEXTIB14;
extern const struct MEXTI_Channel MEXTIB15;
extern const struct MEXTI_Channel MEXTIC0;
extern const struct MEXTI_Channel MEXTIC1;
extern const struct MEXTI_Channel MEXTIC2;
extern const struct MEXTI_Channel MEXTIC3;
extern const struct MEXTI_Channel MEXTIC4;
extern const struct MEXTI_Channel MEXTIC5;
extern const struct MEXTI_Channel MEXTIC6;
extern const struct MEXTI_Channel MEXTIC7;
extern const struct MEXTI_Channel MEXTIC8;
extern const struct MEXTI_Channel MEXTIC9;
extern const struct MEXTI_Channel MEXTIC10;
extern const struct MEXTI_Channel MEXTIC11;
extern const struct MEXTI_Channel MEXTIC12;
extern const struct MEXTI_Channel MEXTIC13;
extern const struct MEXTI_Channel MEXTIC14;
extern const struct MEXTI_Channel MEXTIC15;
extern const struct MEXTI_Channel MEXTID0;
extern const struct MEXTI_Channel MEXTID1;
extern const struct MEXTI_Channel MEXTID2;

#endif /* MCAL_MEXTI_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MUART                                         */
/******************************************************************************/

#ifdef MCAL_MUART_INCLUDED
/* MUART channels */
#ifdef MUART0_PRESENT
extern const struct MUART_Channel MUART0_RX_PA10_TX_PA9;
extern const struct MUART_Channel MUART0_RX_PB7_TX_PB6;

#endif /* MUART0_PRESENT */

#ifdef MUART1_PRESENT
extern const struct MUART_Channel MUART1_RX_PA3_TX_PA2;

#endif /* MUART1_PRESENT */

#ifdef MUART2_PRESENT
extern const struct MUART_Channel MUART2_RX_PB11_TX_PB10;
extern const struct MUART_Channel MUART2_RX_PC11_TX_PC10;

#endif /* MUART2_PRESENT */

#ifdef MUART3_PRESENT
extern const struct MUART_Channel MUART3_RX_PC11_TX_PC10;

#endif /* MUART3_PRESENT */

#ifdef MUART4_PRESENT
extern const struct MUART_Channel MUART4_RX_PD2_TX_PC12;

#endif /* MUART4_PRESENT */


#endif /* MCAL_MUART_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MADC                                          */
/******************************************************************************/

#ifdef MCAL_MADC_INCLUDED
/* MADC peripheral without pin */
extern const struct MADC_Periph MADC0;
extern const struct MADC_Periph MADC1;
extern const struct MADC_Periph MADC2;

/* MADC peripheral with HW trigger */
extern const struct MADC_Periph MADC0_TRIG_TIM0_CH0;
extern const struct MADC_Periph MADC0_TRIG_TIM0_CH1;
extern const struct MADC_Periph MADC0_TRIG_TIM0_CH2;
extern const struct MADC_Periph MADC0_TRIG_TIM1_CH1;
extern const struct MADC_Periph MADC0_TRIG_TIM2_TRGO;
extern const struct MADC_Periph MADC0_TRIG_TIM3_CH3;
extern const struct MADC_Periph MADC0_TRIG_EXTI11;
extern const struct MADC_Periph MADC0_TRIG_TIM7_TRGO;
extern const struct MADC_Periph MADC0_TRIG_SWRCST;
extern const struct MADC_Periph MADC0_TRIG_TIM0_TRGO;
extern const struct MADC_Periph MADC0_TRIG_TIM0_CH3;
extern const struct MADC_Periph MADC0_TRIG_TIM1_TRGO;
extern const struct MADC_Periph MADC0_TRIG_TIM1_CH0;
extern const struct MADC_Periph MADC0_TRIG_TIM2_CH3;
extern const struct MADC_Periph MADC0_TRIG_TIM3_TRGO;
extern const struct MADC_Periph MADC0_TRIG_EXTI15;
extern const struct MADC_Periph MADC0_TRIG_TIM7_CH3;
extern const struct MADC_Periph MADC0_TRIG_SWICST;
extern const struct MADC_Periph MADC1_TRIG_TIM0_CH0;
extern const struct MADC_Periph MADC1_TRIG_TIM0_CH1;
extern const struct MADC_Periph MADC1_TRIG_TIM0_CH2;
extern const struct MADC_Periph MADC1_TRIG_TIM1_CH1;
extern const struct MADC_Periph MADC1_TRIG_TIM2_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM3_CH3;
extern const struct MADC_Periph MADC1_TRIG_EXTI11;
extern const struct MADC_Periph MADC1_TRIG_TIM7_TRGO;
extern const struct MADC_Periph MADC1_TRIG_SWRCST;
extern const struct MADC_Periph MADC1_TRIG_TIM0_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM0_CH3;
extern const struct MADC_Periph MADC1_TRIG_TIM1_TRGO;
extern const struct MADC_Periph MADC1_TRIG_TIM1_CH0;
extern const struct MADC_Periph MADC1_TRIG_TIM2_CH3;
extern const struct MADC_Periph MADC1_TRIG_TIM3_TRGO;
extern const struct MADC_Periph MADC1_TRIG_EXTI15;
extern const struct MADC_Periph MADC1_TRIG_TIM7_CH3;
extern const struct MADC_Periph MADC1_TRIG_SWICST;
extern const struct MADC_Periph MADC2_TRIG_TIM2_CH0;
extern const struct MADC_Periph MADC2_TRIG_TIM1_CH2;
extern const struct MADC_Periph MADC2_TRIG_TIM0_CH2;
extern const struct MADC_Periph MADC2_TRIG_TIM7_CH0;
extern const struct MADC_Periph MADC2_TRIG_TIM7_TRGO;
extern const struct MADC_Periph MADC2_TRIG_TIM4_CH0;
extern const struct MADC_Periph MADC2_TRIG_TIM4_CH2;
extern const struct MADC_Periph MADC2_TRIG_SWRCST;
extern const struct MADC_Periph MADC2_TRIG_TIM0_TRGO;
extern const struct MADC_Periph MADC2_TRIG_TIM0_CH3;
extern const struct MADC_Periph MADC2_TRIG_TIM3_CH2;
extern const struct MADC_Periph MADC2_TRIG_TIM7_CH1;
extern const struct MADC_Periph MADC2_TRIG_TIM7_CH3;
extern const struct MADC_Periph MADC2_TRIG_TIM4_TRGO;
extern const struct MADC_Periph MADC2_TRIG_TIM4_CH3;
extern const struct MADC_Periph MADC2_TRIG_SWICST;

/* MADC channels */
extern const struct MADC_Channel MADC0_IN0_PA0;
extern const struct MADC_Channel MADC0_IN1_PA1;
extern const struct MADC_Channel MADC0_IN2_PA2;
extern const struct MADC_Channel MADC0_IN3_PA3;
extern const struct MADC_Channel MADC0_IN4_PA4;
extern const struct MADC_Channel MADC0_IN5_PA5;
extern const struct MADC_Channel MADC0_IN6_PA6;
extern const struct MADC_Channel MADC0_IN7_PA7;
extern const struct MADC_Channel MADC0_IN8_PB0;
extern const struct MADC_Channel MADC0_IN9_PB1;
extern const struct MADC_Channel MADC0_IN10_PC0;
extern const struct MADC_Channel MADC0_IN11_PC1;
extern const struct MADC_Channel MADC0_IN12_PC2;
extern const struct MADC_Channel MADC0_IN13_PC3;
extern const struct MADC_Channel MADC0_IN14_PC4;
extern const struct MADC_Channel MADC0_IN15_PC5;
extern const struct MADC_Channel MADC1_IN0_PA0;
extern const struct MADC_Channel MADC1_IN1_PA1;
extern const struct MADC_Channel MADC1_IN2_PA2;
extern const struct MADC_Channel MADC1_IN3_PA3;
extern const struct MADC_Channel MADC1_IN4_PA4;
extern const struct MADC_Channel MADC1_IN5_PA5;
extern const struct MADC_Channel MADC1_IN6_PA6;
extern const struct MADC_Channel MADC1_IN7_PA7;
extern const struct MADC_Channel MADC1_IN8_PB0;
extern const struct MADC_Channel MADC1_IN9_PB1;
extern const struct MADC_Channel MADC1_IN10_PC0;
extern const struct MADC_Channel MADC1_IN11_PC1;
extern const struct MADC_Channel MADC1_IN12_PC2;
extern const struct MADC_Channel MADC1_IN13_PC3;
extern const struct MADC_Channel MADC1_IN14_PC4;
extern const struct MADC_Channel MADC1_IN15_PC5;
extern const struct MADC_Channel MADC2_IN0_PA0;
extern const struct MADC_Channel MADC2_IN1_PA1;
extern const struct MADC_Channel MADC2_IN2_PA2;
extern const struct MADC_Channel MADC2_IN3_PA3;
extern const struct MADC_Channel MADC2_IN10_PC0;
extern const struct MADC_Channel MADC2_IN11_PC1;
extern const struct MADC_Channel MADC2_IN12_PC2;
extern const struct MADC_Channel MADC2_IN13_PC3;

#endif /* MCAL_MADC_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MTIM                                          */
/******************************************************************************/

#ifdef MCAL_MTIM_INCLUDED
#ifdef MTIM0_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM0;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM0_PA12_NO_REMAP;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM0_CH0_NO_REMAP;
extern const struct MTIM_Channel MTIM0_CH1_NO_REMAP;
extern const struct MTIM_Channel MTIM0_CH2_NO_REMAP;
extern const struct MTIM_Channel MTIM0_CH3_NO_REMAP;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM0_CH0_PA8_NO_REMAP;
extern const struct MTIM_Channel MTIM0_CH1_PA9_NO_REMAP;
extern const struct MTIM_Channel MTIM0_CH2_PA10_NO_REMAP;
extern const struct MTIM_Channel MTIM0_CH3_PA11_NO_REMAP;

#endif /* MTIM0_PRESENT */

#ifdef MTIM1_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM1;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM1_PA0_NO_REMAP;
extern const struct MTIM_Timer MTIM1_PA15_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Timer MTIM1_PA0_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Timer MTIM1_PA15_GPIO_TIMER1_FULL_REMAP;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM1_CH0_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH1_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH2_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH3_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH0_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH1_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH2_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH3_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH0_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH1_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH2_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH3_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH0_GPIO_TIMER1_FULL_REMAP;
extern const struct MTIM_Channel MTIM1_CH1_GPIO_TIMER1_FULL_REMAP;
extern const struct MTIM_Channel MTIM1_CH2_GPIO_TIMER1_FULL_REMAP;
extern const struct MTIM_Channel MTIM1_CH3_GPIO_TIMER1_FULL_REMAP;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM1_CH0_PA0_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH1_PA1_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH2_PA2_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH3_PA3_NO_REMAP;
extern const struct MTIM_Channel MTIM1_CH0_PA15_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH1_PB3_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH2_PA2_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH3_PA3_GPIO_TIMER1_PARTIAL_REMAP0;
extern const struct MTIM_Channel MTIM1_CH0_PA0_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH1_PA1_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH2_PB10_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH3_PB11_GPIO_TIMER1_PARTIAL_REMAP1;
extern const struct MTIM_Channel MTIM1_CH0_PA15_GPIO_TIMER1_FULL_REMAP;
extern const struct MTIM_Channel MTIM1_CH1_PB3_GPIO_TIMER1_FULL_REMAP;
extern const struct MTIM_Channel MTIM1_CH2_PB10_GPIO_TIMER1_FULL_REMAP;
extern const struct MTIM_Channel MTIM1_CH3_PB11_GPIO_TIMER1_FULL_REMAP;

#endif /* MTIM1_PRESENT */

#ifdef MTIM2_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM2;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM2_PD2_NO_REMAP;
extern const struct MTIM_Timer MTIM2_PD2_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Timer MTIM2_PD2_GPIO_TIMER2_FULL_REMAP;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM2_CH0_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH1_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH2_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH3_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH0_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH1_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH2_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH3_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH0_GPIO_TIMER2_FULL_REMAP;
extern const struct MTIM_Channel MTIM2_CH1_GPIO_TIMER2_FULL_REMAP;
extern const struct MTIM_Channel MTIM2_CH2_GPIO_TIMER2_FULL_REMAP;
extern const struct MTIM_Channel MTIM2_CH3_GPIO_TIMER2_FULL_REMAP;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM2_CH0_PA6_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH1_PA7_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH2_PB0_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH3_PB1_NO_REMAP;
extern const struct MTIM_Channel MTIM2_CH0_PB4_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH1_PB5_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH2_PB0_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH3_PB1_GPIO_TIMER2_PARTIAL_REMAP;
extern const struct MTIM_Channel MTIM2_CH0_PC6_GPIO_TIMER2_FULL_REMAP;
extern const struct MTIM_Channel MTIM2_CH1_PC7_GPIO_TIMER2_FULL_REMAP;
extern const struct MTIM_Channel MTIM2_CH2_PC8_GPIO_TIMER2_FULL_REMAP;
extern const struct MTIM_Channel MTIM2_CH3_PC9_GPIO_TIMER2_FULL_REMAP;

#endif /* MTIM2_PRESENT */

#ifdef MTIM3_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM3;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM3_CH0_NO_REMAP;
extern const struct MTIM_Channel MTIM3_CH1_NO_REMAP;
extern const struct MTIM_Channel MTIM3_CH2_NO_REMAP;
extern const struct MTIM_Channel MTIM3_CH3_NO_REMAP;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM3_CH0_PB6_NO_REMAP;
extern const struct MTIM_Channel MTIM3_CH1_PB7_NO_REMAP;
extern const struct MTIM_Channel MTIM3_CH2_PB8_NO_REMAP;
extern const struct MTIM_Channel MTIM3_CH3_PB9_NO_REMAP;

#endif /* MTIM3_PRESENT */

#ifdef MTIM4_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM4;

/* MTIM timers with pin */
/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM4_CH0_NO_REMAP;
extern const struct MTIM_Channel MTIM4_CH1_NO_REMAP;
extern const struct MTIM_Channel MTIM4_CH2_NO_REMAP;
extern const struct MTIM_Channel MTIM4_CH3_NO_REMAP;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM4_CH0_PA0_NO_REMAP;
extern const struct MTIM_Channel MTIM4_CH1_PA1_NO_REMAP;
extern const struct MTIM_Channel MTIM4_CH2_PA2_NO_REMAP;
extern const struct MTIM_Channel MTIM4_CH3_PA3_NO_REMAP;

#endif /* MTIM4_PRESENT */

#ifdef MTIM5_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM5;

/* MTIM timers with pin */
/* MTIM channels without pin */
/* MTIM channels with pin */
#endif /* MTIM5_PRESENT */

#ifdef MTIM6_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM6;

/* MTIM timers with pin */
/* MTIM channels without pin */
/* MTIM channels with pin */
#endif /* MTIM6_PRESENT */

#ifdef MTIM7_PRESENT
/* MTIM timer without pin */
extern const struct MTIM_Timer MTIM7;

/* MTIM timers with pin */
extern const struct MTIM_Timer MTIM7_PA0_NO_REMAP;

/* MTIM channels without pin */
extern const struct MTIM_Channel MTIM7_CH0_NO_REMAP;
extern const struct MTIM_Channel MTIM7_CH1_NO_REMAP;
extern const struct MTIM_Channel MTIM7_CH2_NO_REMAP;
extern const struct MTIM_Channel MTIM7_CH3_NO_REMAP;

/* MTIM channels with pin */
extern const struct MTIM_Channel MTIM7_CH0_PC6_NO_REMAP;
extern const struct MTIM_Channel MTIM7_CH1_PC7_NO_REMAP;
extern const struct MTIM_Channel MTIM7_CH2_PC8_NO_REMAP;
extern const struct MTIM_Channel MTIM7_CH3_PC9_NO_REMAP;

#endif /* MTIM7_PRESENT */


#endif /* MCAL_MTIM_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MI2C                                         */
/******************************************************************************/

#ifdef MCAL_MI2C_INCLUDED
/* MI2C channels */
#ifdef MI2C0_PRESENT
extern const struct MI2C_Channel MI2C0_SDA_PB7_SCL_PB6;
extern const struct MI2C_Channel MI2C0_SDA_PB9_SCL_PB8;

#endif /* MI2C0_PRESENT */

#ifdef MI2C1_PRESENT
extern const struct MI2C_Channel MI2C1_SDA_PB11_SCL_PB10;

#endif /* MI2C1_PRESENT */


#endif /* MCAL_MI2C_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MSPI                                          */
/******************************************************************************/

#ifdef MCAL_MSPI_INCLUDED
/* MSPI channels */
#ifdef MSPI0_PRESENT
extern const struct MSPI_Channel MSPI0_SCK_PA5_MISO_PA6_MOSI_PA7;
extern const struct MSPI_Channel MSPI0_SCK_PB3_MISO_PB4_MOSI_PB5;

#endif /* MSPI0_PRESENT */

#ifdef MSPI1_PRESENT
extern const struct MSPI_Channel MSPI1_SCK_PB13_MISO_PB14_MOSI_PB15;

#endif /* MSPI1_PRESENT */

#ifdef MSPI2_PRESENT
extern const struct MSPI_Channel MSPI2_SCK_PB3_MISO_PB4_MOSI_PB5;
extern const struct MSPI_Channel MSPI2_SCK_PC10_MISO_PC11_MOSI_PC12;

#endif /* MSPI2_PRESENT */


#endif /* MCAL_MSPI_INCLUDED */


/******************************************************************************/
/* PUBLIC DATA DECLARATIONS FOR MDMA                                          */
/******************************************************************************/

#ifdef MCAL_MDMA_INCLUDED
/* MDMA peripheral */
extern const struct MDMA_Periph MDMA0;
extern const struct MDMA_Periph MDMA1;

/* MDMA channels */
extern const struct MDMA_Channel MDMA0_CH0;
extern const struct MDMA_Channel MDMA0_CH1;
extern const struct MDMA_Channel MDMA0_CH2;
extern const struct MDMA_Channel MDMA0_CH3;
extern const struct MDMA_Channel MDMA0_CH4;
extern const struct MDMA_Channel MDMA0_CH5;
extern const struct MDMA_Channel MDMA0_CH6;
extern const struct MDMA_Channel MDMA1_CH0;
extern const struct MDMA_Channel MDMA1_CH1;
extern const struct MDMA_Channel MDMA1_CH2;
extern const struct MDMA_Channel MDMA1_CH3;
extern const struct MDMA_Channel MDMA1_CH4;

#endif /* MCAL_MDMA_INCLUDED */


#ifdef __cplusplus
}
#endif

#endif // MCAL_CHANNELS_H

// Axivion Enable Style MisraC2012-8.9
