/*******************************************************************************
 *  Copyright (c) 2023 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *  PROJECT          MCAL
 *  PROCESSOR        GD32F30x
 ******************************************************************************/


/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file     mcal_channels.c
 *
 *  \ingroup  MCAL
 *
 *  \brief    Public declarations of MCAL channels
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */

// Axivion Disable Style MisraC2012-8.7: Variable can be declared static in primary file
// Axivion Disable Style MisraC2012-8.9: Global variable can be declared inside function

/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/

#include "mcal_channels.h"


/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MDIO                                           */
/******************************************************************************/

/* MDIO channels without alternate function */
const struct MDIO_Channel MDIOA0 = {&MDIOA, MDIO_PIN0, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA1 = {&MDIOA, MDIO_PIN1, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA2 = {&MDIOA, MDIO_PIN2, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA3 = {&MDIOA, MDIO_PIN3, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA4 = {&MDIOA, MDIO_PIN4, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA5 = {&MDIOA, MDIO_PIN5, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA6 = {&MDIOA, MDIO_PIN6, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA7 = {&MDIOA, MDIO_PIN7, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA8 = {&MDIOA, MDIO_PIN8, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA9 = {&MDIOA, MDIO_PIN9, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA10 = {&MDIOA, MDIO_PIN10, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA11 = {&MDIOA, MDIO_PIN11, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA12 = {&MDIOA, MDIO_PIN12, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA13 = {&MDIOA, MDIO_PIN13, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA14 = {&MDIOA, MDIO_PIN14, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOA15 = {&MDIOA, MDIO_PIN15, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB0 = {&MDIOB, MDIO_PIN0, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB1 = {&MDIOB, MDIO_PIN1, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB2 = {&MDIOB, MDIO_PIN2, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB3 = {&MDIOB, MDIO_PIN3, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB4 = {&MDIOB, MDIO_PIN4, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB5 = {&MDIOB, MDIO_PIN5, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB6 = {&MDIOB, MDIO_PIN6, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB7 = {&MDIOB, MDIO_PIN7, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB8 = {&MDIOB, MDIO_PIN8, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB9 = {&MDIOB, MDIO_PIN9, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB10 = {&MDIOB, MDIO_PIN10, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB11 = {&MDIOB, MDIO_PIN11, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB12 = {&MDIOB, MDIO_PIN12, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB13 = {&MDIOB, MDIO_PIN13, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB14 = {&MDIOB, MDIO_PIN14, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOB15 = {&MDIOB, MDIO_PIN15, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC0 = {&MDIOC, MDIO_PIN0, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC1 = {&MDIOC, MDIO_PIN1, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC2 = {&MDIOC, MDIO_PIN2, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC3 = {&MDIOC, MDIO_PIN3, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC4 = {&MDIOC, MDIO_PIN4, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC5 = {&MDIOC, MDIO_PIN5, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC6 = {&MDIOC, MDIO_PIN6, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC7 = {&MDIOC, MDIO_PIN7, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC8 = {&MDIOC, MDIO_PIN8, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC9 = {&MDIOC, MDIO_PIN9, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC10 = {&MDIOC, MDIO_PIN10, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC11 = {&MDIOC, MDIO_PIN11, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC12 = {&MDIOC, MDIO_PIN12, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC13 = {&MDIOC, MDIO_PIN13, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC14 = {&MDIOC, MDIO_PIN14, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOC15 = {&MDIOC, MDIO_PIN15, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOD0 = {&MDIOD, MDIO_PIN0, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOD1 = {&MDIOD, MDIO_PIN1, MDIO_SCFG_DEFAULT};
const struct MDIO_Channel MDIOD2 = {&MDIOD, MDIO_PIN2, MDIO_SCFG_DEFAULT};

/* MDIO channels with alternate function */
const struct MDIO_Channel MDIOA0_MTIM1_CH0 = {&MDIOA, MDIO_PIN0, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA0_MTIM1_ETI = {&MDIOA, MDIO_PIN0, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA0_MTIM4_CH0 = {&MDIOA, MDIO_PIN0, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA0_MTIM7_ETI = {&MDIOA, MDIO_PIN0, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA1_MTIM1_CH1 = {&MDIOA, MDIO_PIN1, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA1_MTIM4_CH1 = {&MDIOA, MDIO_PIN1, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA2_MUART1_TX = {&MDIOA, MDIO_PIN2, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA2_MTIM1_CH2 = {&MDIOA, MDIO_PIN2, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA2_MTIM4_CH2 = {&MDIOA, MDIO_PIN2, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA3_MUART1_RX = {&MDIOA, MDIO_PIN3, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA3_MTIM1_CH3 = {&MDIOA, MDIO_PIN3, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA3_MTIM4_CH3 = {&MDIOA, MDIO_PIN3, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA4_MSPI0_NSS = {&MDIOA, MDIO_PIN4, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA4_MSPI2_NSS = {&MDIOA, MDIO_PIN4, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA5_MSPI0_SCK = {&MDIOA, MDIO_PIN5, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA6_MSPI0_MISO = {&MDIOA, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA6_MTIM2_CH0 = {&MDIOA, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA7_MSPI0_MOSI = {&MDIOA, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA7_MTIM2_CH1 = {&MDIOA, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA8_MTIM0_CH0 = {&MDIOA, MDIO_PIN8, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA8_CK_OUT = {&MDIOA, MDIO_PIN8, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA9_MUART0_TX = {&MDIOA, MDIO_PIN9, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA9_MTIM0_CH1 = {&MDIOA, MDIO_PIN9, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA10_MUART0_RX = {&MDIOA, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA10_MTIM0_CH2 = {&MDIOA, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA11_MTIM0_CH3 = {&MDIOA, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA12_MTIM0_ETI = {&MDIOA, MDIO_PIN12, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA15_MSPI2_NSS = {&MDIOA, MDIO_PIN15, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA15_MTIM1_CH0 = {&MDIOA, MDIO_PIN15, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOA15_MTIM1_ETI = {&MDIOA, MDIO_PIN15, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOA15_MSPI0_NSS = {&MDIOA, MDIO_PIN15, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB0_MTIM2_CH2 = {&MDIOB, MDIO_PIN0, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB1_MTIM2_CH3 = {&MDIOB, MDIO_PIN1, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB3_MSPI2_SCK = {&MDIOB, MDIO_PIN3, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB3_MTIM1_CH1 = {&MDIOB, MDIO_PIN3, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB3_MSPI0_SCK = {&MDIOB, MDIO_PIN3, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB4_MSPI2_MISO = {&MDIOB, MDIO_PIN4, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOB4_MTIM2_CH0 = {&MDIOB, MDIO_PIN4, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB4_MSPI0_MISO = {&MDIOB, MDIO_PIN4, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOB5_MSPI2_MOSI = {&MDIOB, MDIO_PIN5, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB5_MTIM2_CH1 = {&MDIOB, MDIO_PIN5, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB5_MSPI0_MOSI = {&MDIOB, MDIO_PIN5, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB6_MI2C0_SCL = {&MDIOB, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB6_MTIM3_CH0 = {&MDIOB, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB6_MUART0_TX = {&MDIOB, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB7_MI2C0_SDA = {&MDIOB, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB7_MTIM3_CH1 = {&MDIOB, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB7_MUART0_RX = {&MDIOB, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOB8_MTIM3_CH2 = {&MDIOB, MDIO_PIN8, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB8_MI2C0_SCL = {&MDIOB, MDIO_PIN8, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB9_MTIM3_CH3 = {&MDIOB, MDIO_PIN9, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB9_MI2C0_SDA = {&MDIOB, MDIO_PIN9, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB10_MI2C1_SCL = {&MDIOB, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB10_MUART2_TX = {&MDIOB, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB10_MTIM1_CH2 = {&MDIOB, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB11_MI2C1_SDA = {&MDIOB, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB11_MUART2_RX = {&MDIOB, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOB11_MTIM1_CH3 = {&MDIOB, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB12_MSPI1_NSS = {&MDIOB, MDIO_PIN12, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB13_MSPI1_SCK = {&MDIOB, MDIO_PIN13, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOB14_MSPI1_MISO = {&MDIOB, MDIO_PIN14, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOB15_MSPI1_MOSI = {&MDIOB, MDIO_PIN15, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC6_MTIM7_CH0 = {&MDIOC, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC6_MTIM2_CH0 = {&MDIOC, MDIO_PIN6, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC7_MTIM7_CH1 = {&MDIOC, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC7_MTIM2_CH1 = {&MDIOC, MDIO_PIN7, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC8_MTIM7_CH2 = {&MDIOC, MDIO_PIN8, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC8_MTIM2_CH2 = {&MDIOC, MDIO_PIN8, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC9_MTIM7_CH3 = {&MDIOC, MDIO_PIN9, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC9_MTIM2_CH3 = {&MDIOC, MDIO_PIN9, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC10_MUART3_TX = {&MDIOC, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC10_MUART2_TX = {&MDIOC, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC10_MSPI2_SCK = {&MDIOC, MDIO_PIN10, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC11_MUART3_RX = {&MDIOC, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOC11_MUART2_RX = {&MDIOC, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOC11_MSPI2_MISO = {&MDIOC, MDIO_PIN11, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOC12_MUART4_TX = {&MDIOC, MDIO_PIN12, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOC12_MSPI2_MOSI = {&MDIOC, MDIO_PIN12, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_DEFAULT)};
const struct MDIO_Channel MDIOD2_MTIM2_ETI = {&MDIOD, MDIO_PIN2, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};
const struct MDIO_Channel MDIOD2_MUART4_RX = {&MDIOD, MDIO_PIN2, MDIO_SCFG(MDIO_SPEED_HIGH, MDIO_AFMODE_INPUT)};


/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MEXTI                                          */
/******************************************************************************/

#ifdef MCAL_MEXTI_INCLUDED
/* MEXTI channels */
const struct MEXTI_Channel MEXTIA0 = {&MDIOA0};
const struct MEXTI_Channel MEXTIA1 = {&MDIOA1};
const struct MEXTI_Channel MEXTIA2 = {&MDIOA2};
const struct MEXTI_Channel MEXTIA3 = {&MDIOA3};
const struct MEXTI_Channel MEXTIA4 = {&MDIOA4};
const struct MEXTI_Channel MEXTIA5 = {&MDIOA5};
const struct MEXTI_Channel MEXTIA6 = {&MDIOA6};
const struct MEXTI_Channel MEXTIA7 = {&MDIOA7};
const struct MEXTI_Channel MEXTIA8 = {&MDIOA8};
const struct MEXTI_Channel MEXTIA9 = {&MDIOA9};
const struct MEXTI_Channel MEXTIA10 = {&MDIOA10};
const struct MEXTI_Channel MEXTIA11 = {&MDIOA11};
const struct MEXTI_Channel MEXTIA12 = {&MDIOA12};
const struct MEXTI_Channel MEXTIA13 = {&MDIOA13};
const struct MEXTI_Channel MEXTIA14 = {&MDIOA14};
const struct MEXTI_Channel MEXTIA15 = {&MDIOA15};
const struct MEXTI_Channel MEXTIB0 = {&MDIOB0};
const struct MEXTI_Channel MEXTIB1 = {&MDIOB1};
const struct MEXTI_Channel MEXTIB2 = {&MDIOB2};
const struct MEXTI_Channel MEXTIB3 = {&MDIOB3};
const struct MEXTI_Channel MEXTIB4 = {&MDIOB4};
const struct MEXTI_Channel MEXTIB5 = {&MDIOB5};
const struct MEXTI_Channel MEXTIB6 = {&MDIOB6};
const struct MEXTI_Channel MEXTIB7 = {&MDIOB7};
const struct MEXTI_Channel MEXTIB8 = {&MDIOB8};
const struct MEXTI_Channel MEXTIB9 = {&MDIOB9};
const struct MEXTI_Channel MEXTIB10 = {&MDIOB10};
const struct MEXTI_Channel MEXTIB11 = {&MDIOB11};
const struct MEXTI_Channel MEXTIB12 = {&MDIOB12};
const struct MEXTI_Channel MEXTIB13 = {&MDIOB13};
const struct MEXTI_Channel MEXTIB14 = {&MDIOB14};
const struct MEXTI_Channel MEXTIB15 = {&MDIOB15};
const struct MEXTI_Channel MEXTIC0 = {&MDIOC0};
const struct MEXTI_Channel MEXTIC1 = {&MDIOC1};
const struct MEXTI_Channel MEXTIC2 = {&MDIOC2};
const struct MEXTI_Channel MEXTIC3 = {&MDIOC3};
const struct MEXTI_Channel MEXTIC4 = {&MDIOC4};
const struct MEXTI_Channel MEXTIC5 = {&MDIOC5};
const struct MEXTI_Channel MEXTIC6 = {&MDIOC6};
const struct MEXTI_Channel MEXTIC7 = {&MDIOC7};
const struct MEXTI_Channel MEXTIC8 = {&MDIOC8};
const struct MEXTI_Channel MEXTIC9 = {&MDIOC9};
const struct MEXTI_Channel MEXTIC10 = {&MDIOC10};
const struct MEXTI_Channel MEXTIC11 = {&MDIOC11};
const struct MEXTI_Channel MEXTIC12 = {&MDIOC12};
const struct MEXTI_Channel MEXTIC13 = {&MDIOC13};
const struct MEXTI_Channel MEXTIC14 = {&MDIOC14};
const struct MEXTI_Channel MEXTIC15 = {&MDIOC15};
const struct MEXTI_Channel MEXTID0 = {&MDIOD0};
const struct MEXTI_Channel MEXTID1 = {&MDIOD1};
const struct MEXTI_Channel MEXTID2 = {&MDIOD2};

#endif /* MCAL_MEXTI_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MUART                                          */
/******************************************************************************/

#ifdef MCAL_MUART_INCLUDED
/* MUART channels */
#ifdef MUART0_PRESENT
const struct MUART_Channel MUART0_RX_PA10_TX_PA9 = {&MUART0, &MDIOA10_MUART0_RX, &MDIOA9_MUART0_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};
const struct MUART_Channel MUART0_RX_PB7_TX_PB6 = {&MUART0, &MDIOB7_MUART0_RX, &MDIOB6_MUART0_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = GPIO_USART0_REMAP}};

#endif /* MUART0_PRESENT */

#ifdef MUART1_PRESENT
const struct MUART_Channel MUART1_RX_PA3_TX_PA2 = {&MUART1, &MDIOA3_MUART1_RX, &MDIOA2_MUART1_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};

#endif /* MUART1_PRESENT */

#ifdef MUART2_PRESENT
const struct MUART_Channel MUART2_RX_PB11_TX_PB10 = {&MUART2, &MDIOB11_MUART2_RX, &MDIOB10_MUART2_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};
const struct MUART_Channel MUART2_RX_PC11_TX_PC10 = {&MUART2, &MDIOC11_MUART2_RX, &MDIOC10_MUART2_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = GPIO_USART2_PARTIAL_REMAP}};

#endif /* MUART2_PRESENT */

#ifdef MUART3_PRESENT
const struct MUART_Channel MUART3_RX_PC11_TX_PC10 = {&MUART3, &MDIOC11_MUART3_RX, &MDIOC10_MUART3_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};

#endif /* MUART3_PRESENT */

#ifdef MUART4_PRESENT
const struct MUART_Channel MUART4_RX_PD2_TX_PC12 = {&MUART4, &MDIOD2_MUART4_RX, &MDIOC12_MUART4_TX, {.clkSrc = MUART_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};

#endif /* MUART4_PRESENT */


#endif /* MCAL_MUART_INCLUDED */


/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MADC                                           */
/******************************************************************************/

#ifdef MCAL_MADC_INCLUDED
/* MADC peripheral without pin */
const struct MADC_Periph MADC0 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC1 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC2 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};

/* MADC peripheral with HW trigger */
const struct MADC_Periph MADC0_TRIG_TIM0_CH0 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM0_CH1 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM0_CH2 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM1_CH1 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM2_TRGO = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM3_CH3 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_EXTI11 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM7_TRGO = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_SWRCST = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM0_TRGO = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM0_CH3 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM1_TRGO = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM1_CH0 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM2_CH3 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM3_TRGO = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_EXTI15 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_TIM7_CH3 = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC0_TRIG_SWICST = {&MADC0_Descriptor, MADC0_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM0_CH0 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM0_CH1 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM0_CH2 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM1_CH1 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM2_TRGO = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM3_CH3 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_EXTI11 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM7_TRGO = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_SWRCST = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM0_TRGO = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM0_CH3 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM1_TRGO = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM1_CH0 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM2_CH3 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM3_TRGO = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_EXTI15 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_TIM7_CH3 = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC1_TRIG_SWICST = {&MADC1_Descriptor, MADC1_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM2_CH0 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM1_CH2 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM0_CH2 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM7_CH0 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM7_TRGO = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM4_CH0 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM4_CH2 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_SWRCST = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM0_TRGO = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM0_CH3 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM3_CH2 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM7_CH1 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM7_CH3 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM4_TRGO = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_TIM4_CH3 = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};
const struct MADC_Periph MADC2_TRIG_SWICST = {&MADC2_Descriptor, MADC2_SCFG_DEFAULT};

/* MADC channels */
const struct MADC_Channel MADC0_IN0_PA0 = {&MADC0_IN0_PA0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN1_PA1 = {&MADC0_IN1_PA1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN2_PA2 = {&MADC0_IN2_PA2_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN3_PA3 = {&MADC0_IN3_PA3_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN4_PA4 = {&MADC0_IN4_PA4_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN5_PA5 = {&MADC0_IN5_PA5_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN6_PA6 = {&MADC0_IN6_PA6_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN7_PA7 = {&MADC0_IN7_PA7_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN8_PB0 = {&MADC0_IN8_PB0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN9_PB1 = {&MADC0_IN9_PB1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN10_PC0 = {&MADC0_IN10_PC0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN11_PC1 = {&MADC0_IN11_PC1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN12_PC2 = {&MADC0_IN12_PC2_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN13_PC3 = {&MADC0_IN13_PC3_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN14_PC4 = {&MADC0_IN14_PC4_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC0_IN15_PC5 = {&MADC0_IN15_PC5_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN0_PA0 = {&MADC1_IN0_PA0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN1_PA1 = {&MADC1_IN1_PA1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN2_PA2 = {&MADC1_IN2_PA2_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN3_PA3 = {&MADC1_IN3_PA3_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN4_PA4 = {&MADC1_IN4_PA4_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN5_PA5 = {&MADC1_IN5_PA5_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN6_PA6 = {&MADC1_IN6_PA6_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN7_PA7 = {&MADC1_IN7_PA7_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN8_PB0 = {&MADC1_IN8_PB0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN9_PB1 = {&MADC1_IN9_PB1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN10_PC0 = {&MADC1_IN10_PC0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN11_PC1 = {&MADC1_IN11_PC1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN12_PC2 = {&MADC1_IN12_PC2_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN13_PC3 = {&MADC1_IN13_PC3_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN14_PC4 = {&MADC1_IN14_PC4_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC1_IN15_PC5 = {&MADC1_IN15_PC5_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN0_PA0 = {&MADC2_IN0_PA0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN1_PA1 = {&MADC2_IN1_PA1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN2_PA2 = {&MADC2_IN2_PA2_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN3_PA3 = {&MADC2_IN3_PA3_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN10_PC0 = {&MADC2_IN10_PC0_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN11_PC1 = {&MADC2_IN11_PC1_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN12_PC2 = {&MADC2_IN12_PC2_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};
const struct MADC_Channel MADC2_IN13_PC3 = {&MADC2_IN13_PC3_Descriptor, MADC_CHANNEL_SCFG_DEFAULT};

#endif /* MCAL_MADC_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MTIM                                           */
/******************************************************************************/

#ifdef MCAL_MTIM_INCLUDED
#ifdef MTIM0_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM0 = {&MTIM0_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
const struct MTIM_Timer MTIM0_PA12_NO_REMAP = {&MTIM0_Descriptor, &MDIOA12_MTIM0_ETI, MTIM_TIMER_SCFG_NO_REMAP};

/* MTIM channels without pin */
const struct MTIM_Channel MTIM0_CH0_NO_REMAP = {&MTIM0_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM0_CH1_NO_REMAP = {&MTIM0_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM0_CH2_NO_REMAP = {&MTIM0_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM0_CH3_NO_REMAP = {&MTIM0_CH3_Descriptor, NULL};

/* MTIM channels with pin */
const struct MTIM_Channel MTIM0_CH0_PA8_NO_REMAP = {&MTIM0_CH0_Descriptor, &MDIOA8_MTIM0_CH0};
const struct MTIM_Channel MTIM0_CH1_PA9_NO_REMAP = {&MTIM0_CH1_Descriptor, &MDIOA9_MTIM0_CH1};
const struct MTIM_Channel MTIM0_CH2_PA10_NO_REMAP = {&MTIM0_CH2_Descriptor, &MDIOA10_MTIM0_CH2};
const struct MTIM_Channel MTIM0_CH3_PA11_NO_REMAP = {&MTIM0_CH3_Descriptor, &MDIOA11_MTIM0_CH3};

#endif /* MTIM0_PRESENT */

#ifdef MTIM1_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM1 = {&MTIM1_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
const struct MTIM_Timer MTIM1_PA0_NO_REMAP = {&MTIM1_Descriptor, &MDIOA0_MTIM1_ETI, MTIM_TIMER_SCFG_NO_REMAP};
const struct MTIM_Timer MTIM1_PA15_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_Descriptor, &MDIOA15_MTIM1_ETI, MTIM_TIMER_SCFG_GPIO_TIMER1_PARTIAL_REMAP0};
const struct MTIM_Timer MTIM1_PA0_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_Descriptor, &MDIOA0_MTIM1_ETI, MTIM_TIMER_SCFG_GPIO_TIMER1_PARTIAL_REMAP1};
const struct MTIM_Timer MTIM1_PA15_GPIO_TIMER1_FULL_REMAP = {&MTIM1_Descriptor, &MDIOA15_MTIM1_ETI, MTIM_TIMER_SCFG_GPIO_TIMER1_FULL_REMAP};

/* MTIM channels without pin */
const struct MTIM_Channel MTIM1_CH0_NO_REMAP = {&MTIM1_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH1_NO_REMAP = {&MTIM1_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH2_NO_REMAP = {&MTIM1_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH3_NO_REMAP = {&MTIM1_CH3_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH0_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH1_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH2_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH3_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH3_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH0_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH1_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH2_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH3_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH3_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH0_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH1_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH2_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM1_CH3_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH3_Descriptor, NULL};

/* MTIM channels with pin */
const struct MTIM_Channel MTIM1_CH0_PA0_NO_REMAP = {&MTIM1_CH0_Descriptor, &MDIOA0_MTIM1_CH0};
const struct MTIM_Channel MTIM1_CH1_PA1_NO_REMAP = {&MTIM1_CH1_Descriptor, &MDIOA1_MTIM1_CH1};
const struct MTIM_Channel MTIM1_CH2_PA2_NO_REMAP = {&MTIM1_CH2_Descriptor, &MDIOA2_MTIM1_CH2};
const struct MTIM_Channel MTIM1_CH3_PA3_NO_REMAP = {&MTIM1_CH3_Descriptor, &MDIOA3_MTIM1_CH3};
const struct MTIM_Channel MTIM1_CH0_PA15_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH0_Descriptor, &MDIOA15_MTIM1_CH0};
const struct MTIM_Channel MTIM1_CH1_PB3_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH1_Descriptor, &MDIOB3_MTIM1_CH1};
const struct MTIM_Channel MTIM1_CH2_PA2_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH2_Descriptor, &MDIOA2_MTIM1_CH2};
const struct MTIM_Channel MTIM1_CH3_PA3_GPIO_TIMER1_PARTIAL_REMAP0 = {&MTIM1_CH3_Descriptor, &MDIOA3_MTIM1_CH3};
const struct MTIM_Channel MTIM1_CH0_PA0_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH0_Descriptor, &MDIOA0_MTIM1_CH0};
const struct MTIM_Channel MTIM1_CH1_PA1_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH1_Descriptor, &MDIOA1_MTIM1_CH1};
const struct MTIM_Channel MTIM1_CH2_PB10_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH2_Descriptor, &MDIOB10_MTIM1_CH2};
const struct MTIM_Channel MTIM1_CH3_PB11_GPIO_TIMER1_PARTIAL_REMAP1 = {&MTIM1_CH3_Descriptor, &MDIOB11_MTIM1_CH3};
const struct MTIM_Channel MTIM1_CH0_PA15_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH0_Descriptor, &MDIOA15_MTIM1_CH0};
const struct MTIM_Channel MTIM1_CH1_PB3_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH1_Descriptor, &MDIOB3_MTIM1_CH1};
const struct MTIM_Channel MTIM1_CH2_PB10_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH2_Descriptor, &MDIOB10_MTIM1_CH2};
const struct MTIM_Channel MTIM1_CH3_PB11_GPIO_TIMER1_FULL_REMAP = {&MTIM1_CH3_Descriptor, &MDIOB11_MTIM1_CH3};

#endif /* MTIM1_PRESENT */

#ifdef MTIM2_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM2 = {&MTIM2_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
const struct MTIM_Timer MTIM2_PD2_NO_REMAP = {&MTIM2_Descriptor, &MDIOD2_MTIM2_ETI, MTIM_TIMER_SCFG_NO_REMAP};
const struct MTIM_Timer MTIM2_PD2_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_Descriptor, &MDIOD2_MTIM2_ETI, MTIM_TIMER_SCFG_GPIO_TIMER2_PARTIAL_REMAP};
const struct MTIM_Timer MTIM2_PD2_GPIO_TIMER2_FULL_REMAP = {&MTIM2_Descriptor, &MDIOD2_MTIM2_ETI, MTIM_TIMER_SCFG_GPIO_TIMER2_FULL_REMAP};

/* MTIM channels without pin */
const struct MTIM_Channel MTIM2_CH0_NO_REMAP = {&MTIM2_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH1_NO_REMAP = {&MTIM2_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH2_NO_REMAP = {&MTIM2_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH3_NO_REMAP = {&MTIM2_CH3_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH0_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH1_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH2_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH3_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH3_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH0_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH1_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH2_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM2_CH3_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH3_Descriptor, NULL};

/* MTIM channels with pin */
const struct MTIM_Channel MTIM2_CH0_PA6_NO_REMAP = {&MTIM2_CH0_Descriptor, &MDIOA6_MTIM2_CH0};
const struct MTIM_Channel MTIM2_CH1_PA7_NO_REMAP = {&MTIM2_CH1_Descriptor, &MDIOA7_MTIM2_CH1};
const struct MTIM_Channel MTIM2_CH2_PB0_NO_REMAP = {&MTIM2_CH2_Descriptor, &MDIOB0_MTIM2_CH2};
const struct MTIM_Channel MTIM2_CH3_PB1_NO_REMAP = {&MTIM2_CH3_Descriptor, &MDIOB1_MTIM2_CH3};
const struct MTIM_Channel MTIM2_CH0_PB4_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH0_Descriptor, &MDIOB4_MTIM2_CH0};
const struct MTIM_Channel MTIM2_CH1_PB5_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH1_Descriptor, &MDIOB5_MTIM2_CH1};
const struct MTIM_Channel MTIM2_CH2_PB0_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH2_Descriptor, &MDIOB0_MTIM2_CH2};
const struct MTIM_Channel MTIM2_CH3_PB1_GPIO_TIMER2_PARTIAL_REMAP = {&MTIM2_CH3_Descriptor, &MDIOB1_MTIM2_CH3};
const struct MTIM_Channel MTIM2_CH0_PC6_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH0_Descriptor, &MDIOC6_MTIM2_CH0};
const struct MTIM_Channel MTIM2_CH1_PC7_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH1_Descriptor, &MDIOC7_MTIM2_CH1};
const struct MTIM_Channel MTIM2_CH2_PC8_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH2_Descriptor, &MDIOC8_MTIM2_CH2};
const struct MTIM_Channel MTIM2_CH3_PC9_GPIO_TIMER2_FULL_REMAP = {&MTIM2_CH3_Descriptor, &MDIOC9_MTIM2_CH3};

#endif /* MTIM2_PRESENT */

#ifdef MTIM3_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM3 = {&MTIM3_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
/* MTIM channels without pin */
const struct MTIM_Channel MTIM3_CH0_NO_REMAP = {&MTIM3_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM3_CH1_NO_REMAP = {&MTIM3_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM3_CH2_NO_REMAP = {&MTIM3_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM3_CH3_NO_REMAP = {&MTIM3_CH3_Descriptor, NULL};

/* MTIM channels with pin */
const struct MTIM_Channel MTIM3_CH0_PB6_NO_REMAP = {&MTIM3_CH0_Descriptor, &MDIOB6_MTIM3_CH0};
const struct MTIM_Channel MTIM3_CH1_PB7_NO_REMAP = {&MTIM3_CH1_Descriptor, &MDIOB7_MTIM3_CH1};
const struct MTIM_Channel MTIM3_CH2_PB8_NO_REMAP = {&MTIM3_CH2_Descriptor, &MDIOB8_MTIM3_CH2};
const struct MTIM_Channel MTIM3_CH3_PB9_NO_REMAP = {&MTIM3_CH3_Descriptor, &MDIOB9_MTIM3_CH3};

#endif /* MTIM3_PRESENT */

#ifdef MTIM4_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM4 = {&MTIM4_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
/* MTIM channels without pin */
const struct MTIM_Channel MTIM4_CH0_NO_REMAP = {&MTIM4_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM4_CH1_NO_REMAP = {&MTIM4_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM4_CH2_NO_REMAP = {&MTIM4_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM4_CH3_NO_REMAP = {&MTIM4_CH3_Descriptor, NULL};

/* MTIM channels with pin */
const struct MTIM_Channel MTIM4_CH0_PA0_NO_REMAP = {&MTIM4_CH0_Descriptor, &MDIOA0_MTIM4_CH0};
const struct MTIM_Channel MTIM4_CH1_PA1_NO_REMAP = {&MTIM4_CH1_Descriptor, &MDIOA1_MTIM4_CH1};
const struct MTIM_Channel MTIM4_CH2_PA2_NO_REMAP = {&MTIM4_CH2_Descriptor, &MDIOA2_MTIM4_CH2};
const struct MTIM_Channel MTIM4_CH3_PA3_NO_REMAP = {&MTIM4_CH3_Descriptor, &MDIOA3_MTIM4_CH3};

#endif /* MTIM4_PRESENT */

#ifdef MTIM5_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM5 = {&MTIM5_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
/* MTIM channels without pin */
/* MTIM channels with pin */
#endif /* MTIM5_PRESENT */

#ifdef MTIM6_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM6 = {&MTIM6_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
/* MTIM channels without pin */
/* MTIM channels with pin */
#endif /* MTIM6_PRESENT */

#ifdef MTIM7_PRESENT
/* MTIM timer without pin */
const struct MTIM_Timer MTIM7 = {&MTIM7_Descriptor, NULL, MTIM_TIMER_SCFG_DEFAULT};

/* MTIM timers with pin */
const struct MTIM_Timer MTIM7_PA0_NO_REMAP = {&MTIM7_Descriptor, &MDIOA0_MTIM7_ETI, MTIM_TIMER_SCFG_NO_REMAP};

/* MTIM channels without pin */
const struct MTIM_Channel MTIM7_CH0_NO_REMAP = {&MTIM7_CH0_Descriptor, NULL};
const struct MTIM_Channel MTIM7_CH1_NO_REMAP = {&MTIM7_CH1_Descriptor, NULL};
const struct MTIM_Channel MTIM7_CH2_NO_REMAP = {&MTIM7_CH2_Descriptor, NULL};
const struct MTIM_Channel MTIM7_CH3_NO_REMAP = {&MTIM7_CH3_Descriptor, NULL};

/* MTIM channels with pin */
const struct MTIM_Channel MTIM7_CH0_PC6_NO_REMAP = {&MTIM7_CH0_Descriptor, &MDIOC6_MTIM7_CH0};
const struct MTIM_Channel MTIM7_CH1_PC7_NO_REMAP = {&MTIM7_CH1_Descriptor, &MDIOC7_MTIM7_CH1};
const struct MTIM_Channel MTIM7_CH2_PC8_NO_REMAP = {&MTIM7_CH2_Descriptor, &MDIOC8_MTIM7_CH2};
const struct MTIM_Channel MTIM7_CH3_PC9_NO_REMAP = {&MTIM7_CH3_Descriptor, &MDIOC9_MTIM7_CH3};

#endif /* MTIM7_PRESENT */


#endif /* MCAL_MTIM_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MI2C                                          */
/******************************************************************************/

#ifdef MCAL_MI2C_INCLUDED
/* MI2C channels */
#ifdef MI2C0_PRESENT
const struct MI2C_Channel MI2C0_SDA_PB7_SCL_PB6 = {&MI2C0, &MDIOB7_MI2C0_SDA, &MDIOB6_MI2C0_SCL ,{.clkSrc = MI2C_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};
const struct MI2C_Channel MI2C0_SDA_PB9_SCL_PB8 = {&MI2C0, &MDIOB9_MI2C0_SDA, &MDIOB8_MI2C0_SCL ,{.clkSrc = MI2C_DEFAULT_CLOCK_SOURCE, .remapMask = GPIO_I2C0_REMAP}};

#endif /* MI2C0_PRESENT */

#ifdef MI2C1_PRESENT
const struct MI2C_Channel MI2C1_SDA_PB11_SCL_PB10 = {&MI2C1, &MDIOB11_MI2C1_SDA, &MDIOB10_MI2C1_SCL ,{.clkSrc = MI2C_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};

#endif /* MI2C1_PRESENT */


#endif /* MCAL_MI2C_INCLUDED */

/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MSPI                                          */
/******************************************************************************/

#ifdef MCAL_MSPI_INCLUDED
/* MSPI channels */
#ifdef MSPI0_PRESENT
const struct MSPI_Channel MSPI0_SCK_PA5_MISO_PA6_MOSI_PA7 = {&MSPI0, &MDIOA5_MSPI0_SCK, &MDIOA6_MSPI0_MISO, &MDIOA7_MSPI0_MOSI, NULL, {.clkSrc = MSPI_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};
const struct MSPI_Channel MSPI0_SCK_PB3_MISO_PB4_MOSI_PB5 = {&MSPI0, &MDIOB3_MSPI0_SCK, &MDIOB4_MSPI0_MISO, &MDIOB5_MSPI0_MOSI, NULL, {.clkSrc = MSPI_DEFAULT_CLOCK_SOURCE, .remapMask = GPIO_SPI0_REMAP}};

#endif /* MSPI0_PRESENT */

#ifdef MSPI1_PRESENT
const struct MSPI_Channel MSPI1_SCK_PB13_MISO_PB14_MOSI_PB15 = {&MSPI1, &MDIOB13_MSPI1_SCK, &MDIOB14_MSPI1_MISO, &MDIOB15_MSPI1_MOSI, NULL, {.clkSrc = MSPI_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};

#endif /* MSPI1_PRESENT */

#ifdef MSPI2_PRESENT
const struct MSPI_Channel MSPI2_SCK_PB3_MISO_PB4_MOSI_PB5 = {&MSPI2, &MDIOB3_MSPI2_SCK, &MDIOB4_MSPI2_MISO, &MDIOB5_MSPI2_MOSI, NULL, {.clkSrc = MSPI_DEFAULT_CLOCK_SOURCE, .remapMask = NO_REMAP}};
const struct MSPI_Channel MSPI2_SCK_PC10_MISO_PC11_MOSI_PC12 = {&MSPI2, &MDIOC10_MSPI2_SCK, &MDIOC11_MSPI2_MISO, &MDIOC12_MSPI2_MOSI, NULL, {.clkSrc = MSPI_DEFAULT_CLOCK_SOURCE, .remapMask = GPIO_SPI2_REMAP}};

#endif /* MSPI2_PRESENT */


#endif /* MCAL_MSPI_INCLUDED */


/******************************************************************************/
/* PUBLIC DATA DEFINITIONS FOR MDMA                                           */
/******************************************************************************/

#ifdef MCAL_MDMA_INCLUDED
/* MDMA peripheral */
const struct MDMA_Periph MDMA0 = {&MDMA0_Descriptor};
const struct MDMA_Periph MDMA1 = {&MDMA1_Descriptor};

/* MDMA channels */
const struct MDMA_Channel MDMA0_CH0 = {&MDMA0_CH0_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA0_CH1 = {&MDMA0_CH1_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA0_CH2 = {&MDMA0_CH2_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA0_CH3 = {&MDMA0_CH3_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA0_CH4 = {&MDMA0_CH4_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA0_CH5 = {&MDMA0_CH5_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA0_CH6 = {&MDMA0_CH6_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA1_CH0 = {&MDMA1_CH0_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA1_CH1 = {&MDMA1_CH1_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA1_CH2 = {&MDMA1_CH2_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA1_CH3 = {&MDMA1_CH3_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};
const struct MDMA_Channel MDMA1_CH4 = {&MDMA1_CH4_Descriptor, MDMA_CHANNEL_SCFG_DEFAULT};

#endif /* MCAL_MDMA_INCLUDED */

// Axivion Enable Style MisraC2012-8.9
// Axivion Enable Style MisraC2012-8.7
