# Enable Zephyr Kernel features
CONFIG_HEAP_MEM_POOL_SIZE=256
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_SYS_CLOCK_EXISTS=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

# Enable console and printk
CONFIG_CONSOLE=y
CONFIG_PRINTK=y

# Enable CAN driver
# Enable SPI driver
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_SPI_INIT_PRIORITY=50
CONFIG_SPI_ASYNC=y # Enable asynchronous SPI operations

# Enable custom DBAL configuration
CONFIG_DBAL_CROSS_CONNECTION=y
CONFIG_SPI_MCUX_FLEXCOMM=y
CONFIG_DBAL_TARGET_ADDRESS=0x00

# Enable ZTest for unit testing
# CONFIG_ZTEST=y