/*******************************************************************************
 *  Copyright (c) 2025 BSH Hausgeraete GmbH,
 *  Carl-Wery-Str. 34, 81739 Munich, Germany, www.bsh-group.de
 *
 *  All rights reserved. This program and the accompanying materials
 *  are protected by international copyright laws.
 *  Please contact copyright holder for licensing information.
 *
 *******************************************************************************
 *   PROJECT          Generic SW
 *   COMP_ABBREV      INTP      
 ******************************************************************************/


#ifndef INTPRIOTBL_AUTO_H
#define INTPRIOTBL_AUTO_H

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* DOCUMENTATION                                                              */
/******************************************************************************/
/** \file     IntPrioTbl_auto.h
 *
 *  \brief    Interrupt priority table
 *
 *  \note     This file is automatically generated. Do not modify this file
 *            manually.
 */


/******************************************************************************/
/* INCLUDES                                                                   */
/******************************************************************************/

#include "processor.h"

/******************************************************************************/
/* PUBLIC DEFINITIONS                                                         */
/******************************************************************************/

#define    INTP_DEFAULT_PRIO    7UL

/******************************************************************************/
/* PUBLIC TYPE DEFINITIONS                                                    */
/******************************************************************************/

struct INTP_PrioConfig
{
    IRQn_Type      vectorNumber;
    uint8_t            priority;
};

/******************************************************************************/
/* PUBLIC DATA DECLARATIONS                                                   */
/******************************************************************************/

#ifdef INTP_CONFIG_ENABLED
extern const struct INTP_PrioConfig INTP_PrioTbl[0UL];
extern const uint32_t INTP_PrioTblSize;
#endif

#ifdef __cplusplus
}
#endif

#endif // INTPRIOTBL_AUTO_H
 
